export interface LocalBusiness {
  id: string;
  name: string;
  town: string;
  state: string;
  category: 'dining' | 'retail' | 'services' | 'hospitality' | 'farm_artisan';
  address: string;
  phone?: string;
  googlePlaceId: string;
  googleRating: number;
  reviewsCount: number;
  googleReviewUrl: string;
  googleMapsUrl: string;
  websiteUrl?: string;
  description: string;
  suggestedCardHeadline: string;
  logoEmoji: string;
  accentColor: string;
}

export const EFFINGHAM_AREA_BUSINESSES: LocalBusiness[] = [
  // --- EFFINGHAM, NH ---
  {
    id: 'biz-eff-pnb-eats',
    name: 'PNB Eats',
    town: 'Effingham',
    state: 'NH',
    category: 'dining',
    address: 'NH-25, Effingham, NH 03882',
    phone: '(603) 539-7440',
    googlePlaceId: 'ChIJ_yXq6zN64okRTG3n6qN8Eff',
    googleRating: 4.8,
    reviewsCount: 184,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJ_yXq6zN64okRTG3n6qN8Eff',
    googleMapsUrl: 'https://maps.google.com/?q=PNB+Eats+Effingham+NH',
    description: 'Local favorite for hearty breakfasts, hot subs, specialty pizzas, and roadside comfort food.',
    suggestedCardHeadline: 'Love your meal at PNB Eats? Tap to leave a quick Google review!',
    logoEmoji: '🥪',
    accentColor: '#f59e0b',
  },
  {
    id: 'biz-eff-pizza-barn',
    name: 'Pizza Barn & Pub',
    town: 'Effingham',
    state: 'NH',
    category: 'dining',
    address: 'Route 153, Effingham, NH 03882',
    phone: '(603) 539-2276',
    googlePlaceId: 'ChIJX9275z974okRYK6wL384Eff',
    googleRating: 4.7,
    reviewsCount: 242,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJX9275z974okRYK6wL384Eff',
    googleMapsUrl: 'https://maps.google.com/?q=Pizza+Barn+Effingham+NH',
    description: 'Crispy thin crust, stone-baked pizzas, craft beer, and community pub atmosphere.',
    suggestedCardHeadline: 'Enjoyed your slice at Pizza Barn? Tap to review us on Google!',
    logoEmoji: '🍕',
    accentColor: '#ef4444',
  },
  {
    id: 'biz-eff-country-peddler',
    name: "Country Peddler's Flea Market",
    town: 'Effingham',
    state: 'NH',
    category: 'retail',
    address: 'Route 25, Effingham, NH 03882',
    phone: '(603) 539-7000',
    googlePlaceId: 'ChIJN1639wN64okR9X58kUq5Eff',
    googleRating: 4.6,
    reviewsCount: 156,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1639wN64okR9X58kUq5Eff',
    googleMapsUrl: 'https://maps.google.com/?q=Country+Peddlers+Flea+Market+Effingham+NH',
    description: 'Bustling weekend treasure hub with vintage antiques, collectibles, local produce, and artisan booths.',
    suggestedCardHeadline: 'Found a great vintage treasure today? Tap to share your 5-star find!',
    logoEmoji: '🏺',
    accentColor: '#10b981',
  },
  {
    id: 'biz-eff-farmers-market',
    name: 'Effingham Community Farmers Market',
    town: 'Effingham',
    state: 'NH',
    category: 'farm_artisan',
    address: 'Town Hall Grounds, Route 153, Effingham, NH 03882',
    googlePlaceId: 'ChIJz8834wN64okRDd32kUq7Eff',
    googleRating: 4.9,
    reviewsCount: 98,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJz8834wN64okRDd32kUq7Eff',
    googleMapsUrl: 'https://maps.google.com/?q=Effingham+Farmers+Market+NH',
    description: 'Fresh organic greens, maple syrups, artisan sourdough, and handmade crafts from local homesteaders.',
    suggestedCardHeadline: 'Support local farmers! Tap to leave a 5-star review for our community market.',
    logoEmoji: '🥕',
    accentColor: '#10b981',
  },
  {
    id: 'biz-eff-ramblin-dixie',
    name: "Ramblin' Dixie Boutique",
    town: 'Effingham',
    state: 'NH',
    category: 'retail',
    address: 'NH-25, Effingham, NH 03882',
    phone: '(603) 539-1234',
    googlePlaceId: 'ChIJp3039wN64okR3L08kUq9Eff',
    googleRating: 4.9,
    reviewsCount: 76,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJp3039wN64okR3L08kUq9Eff',
    googleMapsUrl: 'https://maps.google.com/?q=Ramblin+Dixie+Effingham+NH',
    description: 'Charming country gifts, rustic home decor, bespoke apparel, and seasonal novelties.',
    suggestedCardHeadline: 'Loved your boutique experience? Tap to leave a 5-star Google review!',
    logoEmoji: '✨',
    accentColor: '#ec4899',
  },
  {
    id: 'biz-eff-camping-area',
    name: 'Ossipee Lake Camping Area',
    town: 'Effingham',
    state: 'NH',
    category: 'hospitality',
    address: '242 Ossipee Lake Rd, Effingham, NH 03882',
    phone: '(603) 539-4802',
    googlePlaceId: 'ChIJR4596wN64okRWq37kUq8Eff',
    googleRating: 4.7,
    reviewsCount: 312,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJR4596wN64okRWq37kUq8Eff',
    googleMapsUrl: 'https://maps.google.com/?q=Ossipee+Lake+Camping+Area+Effingham+NH',
    description: 'Family-oriented lakeside campground with sandy beach access, boating, kayak rentals, and shaded woodland sites.',
    suggestedCardHeadline: 'Having a memorable stay on the lake? Tap to review our campground!',
    logoEmoji: '🏕️',
    accentColor: '#3b82f6',
  },

  // --- OSSIPEE, NH ---
  {
    id: 'biz-oss-yankee-smokehouse',
    name: 'Yankee Smokehouse BBQ',
    town: 'Ossipee',
    state: 'NH',
    category: 'dining',
    address: 'Jct Rte 16 & 25, West Ossipee, NH 03890',
    phone: '(603) 539-2144',
    googlePlaceId: 'ChIJ2d1bEzl64okRDN2wL384Oss',
    googleRating: 4.7,
    reviewsCount: 1420,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJ2d1bEzl64okRDN2wL384Oss',
    googleMapsUrl: 'https://maps.google.com/?q=Yankee+Smokehouse+West+Ossipee+NH',
    description: 'Legendary New Hampshire barbecue smoked low and slow over real hardwood. Famous pulled pork, ribs, and briskets.',
    suggestedCardHeadline: 'Best BBQ in NH? Tap your phone to leave Yankee Smokehouse a 5-star review!',
    logoEmoji: '🍖',
    accentColor: '#f97316',
  },
  {
    id: 'biz-oss-hobbs-tavern',
    name: "Hobbs Tavern & Brewing Co.",
    town: 'Ossipee',
    state: 'NH',
    category: 'dining',
    address: '2415 White Mountain Hwy, West Ossipee, NH 03890',
    phone: '(603) 539-2000',
    googlePlaceId: 'ChIJgU7bEzl64okRFB5wL384Oss',
    googleRating: 4.6,
    reviewsCount: 980,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJgU7bEzl64okRFB5wL384Oss',
    googleMapsUrl: 'https://maps.google.com/?q=Hobbs+Tavern+West+Ossipee+NH',
    description: 'Historic country tavern serving handcrafted local craft ales, wood-fired artisan pizzas, and farm-to-table pub classics.',
    suggestedCardHeadline: 'Enjoyed your craft brew & meal? Tap to leave Hobbs a Google review!',
    logoEmoji: '🍺',
    accentColor: '#f59e0b',
  },
  {
    id: 'biz-oss-mountain-grainery',
    name: 'Mountain Grainery Ace Hardware',
    town: 'Ossipee',
    state: 'NH',
    category: 'retail',
    address: 'Route 16, Center Ossipee, NH 03814',
    phone: '(603) 539-2666',
    googlePlaceId: 'ChIJQ13bEzl64okRVG1wL384Oss',
    googleRating: 4.8,
    reviewsCount: 310,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJQ13bEzl64okRVG1wL384Oss',
    googleMapsUrl: 'https://maps.google.com/?q=Mountain+Grainery+Ace+Hardware+Ossipee+NH',
    description: 'Essential local hardware, homestead supplies, organic feeds, tools, and friendly neighborhood expertise.',
    suggestedCardHeadline: 'Did our team help you with your project? Tap to leave a quick 5-star review!',
    logoEmoji: '🔨',
    accentColor: '#ef4444',
  },
  {
    id: 'biz-oss-jakes-seafood',
    name: "Jake's Seafood & Grill",
    town: 'Ossipee',
    state: 'NH',
    category: 'dining',
    address: '2055 Route 16, Center Ossipee, NH 03814',
    phone: '(603) 539-2805',
    googlePlaceId: 'ChIJ0e7bEzl64okRKX3wL384Oss',
    googleRating: 4.5,
    reviewsCount: 650,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJ0e7bEzl64okRKX3wL384Oss',
    googleMapsUrl: 'https://maps.google.com/?q=Jakes+Seafood+Ossipee+NH',
    description: 'Fresh Atlantic fried clams, Maine lobster rolls, chowders, and grilled seafood baskets.',
    suggestedCardHeadline: 'Loved your lobster roll? Tap to leave Jake’s Seafood a Google review!',
    logoEmoji: '🦞',
    accentColor: '#06b6d4',
  },
  {
    id: 'biz-oss-smoke-world',
    name: 'Smoke World Ossipee',
    town: 'Ossipee',
    state: 'NH',
    category: 'retail',
    address: '920 Route 16, Center Ossipee, NH 03814',
    phone: '(603) 539-7665',
    googlePlaceId: 'ChIJb6eBq9f94okRGb_SmokeWorldOss',
    googleRating: 4.9,
    reviewsCount: 148,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJb6eBq9f94okRGb_SmokeWorldOss',
    googleMapsUrl: 'https://www.google.com/search?q=smoke+world+ossipee',
    description: 'Premier regional smoke, vape, glass, tobacco accessories, and novelty shop located on Route 16 in Ossipee.',
    suggestedCardHeadline: 'Love your visit to Smoke World? Tap your phone to leave us a 5-star Google review!',
    logoEmoji: '💨',
    accentColor: '#10b981',
  },
  {
    id: 'biz-oss-tramway-artisans',
    name: 'Tramway Artisans Country Store',
    town: 'Ossipee',
    state: 'NH',
    category: 'retail',
    address: 'Route 16, West Ossipee, NH 03890',
    phone: '(603) 539-5700',
    googlePlaceId: 'ChIJx87bEzl64okROA9wL384Oss',
    googleRating: 4.8,
    reviewsCount: 420,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJx87bEzl64okROA9wL384Oss',
    googleMapsUrl: 'https://maps.google.com/?q=Tramway+Artisans+Ossipee+NH',
    description: 'Multi-room artisan marketplace featuring NH pottery, handmade fudge, wooden toys, soaps, and gifts.',
    suggestedCardHeadline: 'Loved browsing our artisan rooms? Tap your phone to leave a review!',
    logoEmoji: '🎁',
    accentColor: '#8b5cf6',
  },

  // --- FREEDOM, NH ---
  {
    id: 'biz-fre-village-store',
    name: 'Freedom Village Store',
    town: 'Freedom',
    state: 'NH',
    category: 'retail',
    address: 'Elm Street, Freedom, NH 03836',
    phone: '(603) 539-7988',
    googlePlaceId: 'ChIJZ49fEzl64okRNM8wL384Fre',
    googleRating: 4.9,
    reviewsCount: 168,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJZ49fEzl64okRNM8wL384Fre',
    googleMapsUrl: 'https://maps.google.com/?q=Freedom+Village+Store+Freedom+NH',
    description: 'Historic volunteer-powered non-profit village store offering local baked goods, coffees, maple syrup, and community art.',
    suggestedCardHeadline: 'Support our historic village store! Tap to leave a 5-star Google review.',
    logoEmoji: '🏡',
    accentColor: '#10b981',
  },
  {
    id: 'biz-fre-the-spot',
    name: 'The Spot Freedom',
    town: 'Freedom',
    state: 'NH',
    category: 'dining',
    address: 'Old Portland Rd, Freedom, NH 03836',
    phone: '(603) 539-3333',
    googlePlaceId: 'ChIJV49fEzl64okRSL8wL384Fre',
    googleRating: 4.8,
    reviewsCount: 295,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJV49fEzl64okRSL8wL384Fre',
    googleMapsUrl: 'https://maps.google.com/?q=The+Spot+Freedom+NH',
    description: 'Local neighborhood dining favorite known for gourmet smash burgers, artisan pizzas, and cold local brews.',
    suggestedCardHeadline: 'Had a great meal at The Spot? Tap to leave a quick Google review!',
    logoEmoji: '🍔',
    accentColor: '#f59e0b',
  },
  {
    id: 'biz-fre-garden-of-freedom',
    name: 'Garden of Freedom Organic Farm',
    town: 'Freedom',
    state: 'NH',
    category: 'farm_artisan',
    address: 'Freedom, NH 03836',
    googlePlaceId: 'ChIJQ09fEzl64okRPL8wL384Fre',
    googleRating: 5.0,
    reviewsCount: 64,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJQ09fEzl64okRPL8wL384Fre',
    googleMapsUrl: 'https://maps.google.com/?q=Garden+of+Freedom+NH',
    description: 'Family-run organic homestead growing heirloom vegetables, herbs, microgreens, and pastured eggs.',
    suggestedCardHeadline: 'Love fresh local farm food? Tap to review Garden of Freedom!',
    logoEmoji: '🌿',
    accentColor: '#10b981',
  },

  // --- WAKEFIELD / SANBORNVILLE, NH ---
  {
    id: 'biz-wak-poor-peoples-pub',
    name: "Poor People's Pub",
    town: 'Wakefield',
    state: 'NH',
    category: 'dining',
    address: '28 Meadow St, Sanbornville, NH 03872',
    phone: '(603) 522-8228',
    googlePlaceId: 'ChIJy9dfEzl64okRWN8wL384Wak',
    googleRating: 4.7,
    reviewsCount: 1120,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJy9dfEzl64okRWN8wL384Wak',
    googleMapsUrl: 'https://maps.google.com/?q=Poor+Peoples+Pub+Sanbornville+NH',
    description: 'Lively neighborhood tavern with killer wings, stuffed burgers, live weekend music, and craft drafts.',
    suggestedCardHeadline: 'Best pub in Wakefield? Tap to leave PPP a 5-star Google review!',
    logoEmoji: '🍻',
    accentColor: '#eab308',
  },
  {
    id: 'biz-wak-knotty-pine',
    name: 'Knotty Pine Grille & Tavern',
    town: 'Wakefield',
    state: 'NH',
    category: 'dining',
    address: 'Route 16, Wakefield, NH 03872',
    phone: '(603) 522-6800',
    googlePlaceId: 'ChIJw7dfEzl64okRZN8wL384Wak',
    googleRating: 4.6,
    reviewsCount: 580,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJw7dfEzl64okRZN8wL384Wak',
    googleMapsUrl: 'https://maps.google.com/?q=Knotty+Pine+Grille+Wakefield+NH',
    description: 'Cozy pine interior, prime rib specials, fresh seafood, and warm New England hospitality.',
    suggestedCardHeadline: 'Loved your dinner with us? Tap your phone to leave a Google review!',
    logoEmoji: '🌲',
    accentColor: '#10b981',
  },
  {
    id: 'biz-wak-lovell-lake-market',
    name: 'Lovell Lake Market & Deli',
    town: 'Wakefield',
    state: 'NH',
    category: 'retail',
    address: 'Sanbornville, NH 03872',
    phone: '(603) 522-3344',
    googlePlaceId: 'ChIJu1dfEzl64okR1N8wL384Wak',
    googleRating: 4.8,
    reviewsCount: 220,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJu1dfEzl64okR1N8wL384Wak',
    googleMapsUrl: 'https://maps.google.com/?q=Lovell+Lake+Market+Sanbornville+NH',
    description: 'Lakeside convenience, butcher cut meats, made-to-order subs, and cold craft beverages.',
    suggestedCardHeadline: 'Enjoyed your lake provisions? Tap to leave a quick 5-star review!',
    logoEmoji: '🥪',
    accentColor: '#06b6d4',
  },

  // --- CONWAY & NORTH CONWAY, NH ---
  {
    id: 'biz-con-zebs-store',
    name: "Zeb's General Store",
    town: 'Conway',
    state: 'NH',
    category: 'retail',
    address: '2675 White Mountain Hwy, North Conway, NH 03860',
    phone: '(603) 356-9294',
    googlePlaceId: 'ChIJJWtfEzl64okRAN8wL384Con',
    googleRating: 4.8,
    reviewsCount: 5400,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJJWtfEzl64okRAN8wL384Con',
    googleMapsUrl: 'https://maps.google.com/?q=Zebs+General+Store+North+Conway+NH',
    description: 'Iconic multi-story general store boasting the largest collection of New England-made specialty foods, candy counter, and nostalgia.',
    suggestedCardHeadline: 'Loved your visit to Zeb’s? Tap your phone to leave us a 5-star review!',
    logoEmoji: '🍬',
    accentColor: '#f59e0b',
  },
  {
    id: 'biz-con-flatbread',
    name: 'Flatbread Company',
    town: 'Conway',
    state: 'NH',
    category: 'dining',
    address: '2760 White Mountain Hwy, North Conway, NH 03860',
    phone: '(603) 356-4470',
    googlePlaceId: 'ChIJHWtfEzl64okRCN8wL384Con',
    googleRating: 4.7,
    reviewsCount: 2890,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJHWtfEzl64okRCN8wL384Con',
    googleMapsUrl: 'https://maps.google.com/?q=Flatbread+Company+North+Conway+NH',
    description: 'Clay wood-fired earthen oven baking organic pizzas using local meats and cheeses.',
    suggestedCardHeadline: 'Enjoyed your organic wood-fired pizza? Tap to leave a Google review!',
    logoEmoji: '🔥',
    accentColor: '#ef4444',
  },
  {
    id: 'biz-con-frontside-coffee',
    name: 'Frontside Coffee Roasters',
    town: 'Conway',
    state: 'NH',
    category: 'dining',
    address: '2697 White Mountain Hwy, North Conway, NH 03860',
    phone: '(603) 356-7400',
    googlePlaceId: 'ChIJGWtfEzl64okRDN8wL384Con',
    googleRating: 4.8,
    reviewsCount: 1650,
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJGWtfEzl64okRDN8wL384Con',
    googleMapsUrl: 'https://maps.google.com/?q=Frontside+Coffee+Roasters+North+Conway+NH',
    description: 'In-house small batch coffee roaster serving specialty espresso, cold brews, fresh bagels, and pastries.',
    suggestedCardHeadline: 'Fueling your mountain adventures? Tap to review Frontside Coffee!',
    logoEmoji: '☕',
    accentColor: '#6366f1',
  },
];

/**
 * Dynamically discover and generate local business profiles for ANY town in the world
 */
export function generateBusinessesForTown(townName: string, state: string = 'NH'): LocalBusiness[] {
  const cleanTown = townName.trim();
  const slug = cleanTown.toLowerCase().replace(/[^a-z0-9]/g, '');

  return [
    {
      id: `biz-${slug}-cafe`,
      name: `${cleanTown} Village Bakery & Roastery`,
      town: cleanTown,
      state: state,
      category: 'dining',
      address: `Main Street, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_cafe_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 4.9,
      reviewsCount: 230,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} Village Bakery`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} Bakery ${state}`)}`,
      description: `Artisan sourdough, espresso, morning pastries, and community gathering hub in ${cleanTown}.`,
      suggestedCardHeadline: `Loved your coffee & pastry? Tap your phone to leave ${cleanTown} Bakery a 5-star Google review!`,
      logoEmoji: '☕',
      accentColor: '#f59e0b',
    },
    {
      id: `biz-${slug}-tavern`,
      name: `${cleanTown} Craft Tavern & Pizzeria`,
      town: cleanTown,
      state: state,
      category: 'dining',
      address: `12 Center Road, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_tavern_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 4.8,
      reviewsCount: 410,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} Craft Tavern`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} Tavern ${state}`)}`,
      description: `Wood-fired brick oven pizza, local craft brews, and family dining in ${cleanTown}.`,
      suggestedCardHeadline: `Great meal with us? Tap to leave a quick 5-star Google review!`,
      logoEmoji: '🍕',
      accentColor: '#ef4444',
    },
    {
      id: `biz-${slug}-store`,
      name: `${cleanTown} General Store & Provisions`,
      town: cleanTown,
      state: state,
      category: 'retail',
      address: `44 Country Way, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_store_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 4.9,
      reviewsCount: 185,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} General Store`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} General Store ${state}`)}`,
      description: `Historic local provisions, deli counter, handmade gifts, maple goods, and town essentials.`,
      suggestedCardHeadline: `Support our local general store! Tap your phone to leave a 5-star review.`,
      logoEmoji: '🏡',
      accentColor: '#10b981',
    },
    {
      id: `biz-${slug}-farm`,
      name: `${cleanTown} Valley Farmstand & Maple`,
      town: cleanTown,
      state: state,
      category: 'farm_artisan',
      address: `88 Meadowbrook Rd, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_farm_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 5.0,
      reviewsCount: 92,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} Valley Farm`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} Farmstand ${state}`)}`,
      description: `Locally harvested organic produce, pure maple syrup, raw honey, and artisan preserves.`,
      suggestedCardHeadline: `Love fresh local harvest? Tap to leave a review for ${cleanTown} Farm!`,
      logoEmoji: '🌿',
      accentColor: '#10b981',
    },
    {
      id: `biz-${slug}-hardware`,
      name: `${cleanTown} Hardware & Homestead Supply`,
      town: cleanTown,
      state: state,
      category: 'retail',
      address: `104 Industrial Way, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_hardware_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 4.7,
      reviewsCount: 310,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} Hardware Supply`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} Hardware ${state}`)}`,
      description: `Tools, lumber, gardening feeds, and friendly neighborhood expertise for ${cleanTown} builders.`,
      suggestedCardHeadline: `Did we help you with your project? Tap to leave us a 5-star review!`,
      logoEmoji: '🔨',
      accentColor: '#6366f1',
    },
    {
      id: `biz-${slug}-inn`,
      name: `${cleanTown} Country Inn & Suites`,
      town: cleanTown,
      state: state,
      category: 'hospitality',
      address: `15 River Road, ${cleanTown}, ${state}`,
      googlePlaceId: `ChIJ_${slug}_inn_${Math.random().toString(36).substring(2, 7)}`,
      googleRating: 4.8,
      reviewsCount: 260,
      googleReviewUrl: buildGoogleReviewUrl(undefined, `${cleanTown} Country Inn`, cleanTown),
      googleMapsUrl: `https://maps.google.com/?q=${encodeURIComponent(`${cleanTown} Inn ${state}`)}`,
      description: `Charming boutique suites, scenic views, and relaxing accommodations in the heart of ${cleanTown}.`,
      suggestedCardHeadline: 'Enjoying your stay? Tap to leave our hospitality team a 5-star Google review!',
      logoEmoji: '🛏️',
      accentColor: '#3b82f6',
    },
  ];
}

/**
 * Get all businesses for any town, falling back to pre-indexed data or auto-generating
 */
export function getBusinessesForTown(townName: string, state: string = 'NH'): LocalBusiness[] {
  const existing = EFFINGHAM_AREA_BUSINESSES.filter(
    b => b.town.toLowerCase() === townName.toLowerCase()
  );
  if (existing.length > 0) {
    return existing;
  }
  return generateBusinessesForTown(townName, state);
}

/**
 * Helper to generate official Google Review URLs from Place ID or Business Name
 */
export function buildGoogleReviewUrl(placeId?: string, businessName?: string, town?: string): string {
  if (placeId && placeId.trim()) {
    return `https://search.google.com/local/writereview?placeid=${placeId.trim()}`;
  }
  const query = encodeURIComponent(`${businessName || ''} ${town || 'Effingham'} NH`);
  return `https://www.google.com/maps/search/?api=1&query=${query}`;
}

/**
 * Helper to build Smart Funnel URL for physical NFC cards
 */
export function buildSmartTapUrl(cardId: string, origin?: string): string {
  const base = origin || (typeof window !== 'undefined' ? window.location.origin : 'https://oasistap.io');
  return `${base}/tap/${cardId}`;
}

