import { ReviewProduct, NfcCardConfig, TapLog, PrivateFeedback, SellerProfile, ShoutoutPost, TownNode } from './types';

export const INITIAL_TOWNS: TownNode[] = [
  {
    id: 'town-effingham',
    name: 'Effingham',
    state: 'NH',
    fullName: 'Effingham, NH',
    tagline: 'North Gateway Hub',
    icon: '🏡',
    status: 'peak_flow',
    boutiquesCount: 4,
    routesCount: 12,
    occupancyLattice: 92,
    vanguardLead: 'Sean Martin',
    dispatchPhone: '(508) 507-0305',
    description: 'Premier independent discovery node with active sourdough bakehouses, woodcarvers, and high-frequency tap stations.',
    accentColor: '#f59e0b',
    joinedDate: '2026-01-01',
  },
  {
    id: 'town-freedom',
    name: 'Freedom',
    state: 'NH',
    fullName: 'Freedom, NH',
    tagline: 'Central Hub',
    icon: '🌳',
    status: 'stable',
    boutiquesCount: 2,
    routesCount: 4,
    occupancyLattice: 45,
    vanguardLead: 'Local Dave Courier',
    dispatchPhone: '(603) 555-0199',
    description: 'Central logistics waypoint providing rapid 15-minute courier runs and local artisan connections.',
    accentColor: '#6366f1',
    joinedDate: '2026-02-01',
  },
  {
    id: 'town-ossipee',
    name: 'Ossipee',
    state: 'NH',
    fullName: 'Ossipee, NH',
    tagline: 'Mountain Node',
    icon: '🏔️',
    status: 'stable',
    boutiquesCount: 2,
    routesCount: 8,
    occupancyLattice: 78,
    vanguardLead: 'Sarah NH Forage & Flora',
    dispatchPhone: '(603) 555-0812',
    description: 'Mountain valley hub specializing in wild foraged botanicals, raw honey, and wood-fired pizzerias.',
    accentColor: '#10b981',
    joinedDate: '2026-02-15',
  },
  {
    id: 'town-conway',
    name: 'Conway',
    state: 'NH',
    fullName: 'Conway, NH',
    tagline: 'Northern Apex Node',
    icon: '⚡',
    status: 'peak_flow',
    boutiquesCount: 3,
    routesCount: 6,
    occupancyLattice: 84,
    vanguardLead: 'Apex Precision Automotive',
    dispatchPhone: '(603) 555-0233',
    description: 'High-volume commercial node powering smart automotive services and high-traffic retail.',
    accentColor: '#3b82f6',
    joinedDate: '2026-03-01',
  },
];

export const INITIAL_SELLERS: SellerProfile[] = [
  {
    id: 'seller-sean',
    name: 'Sean Martin • Oasis Vanguard',
    handle: '@sean_vanguard',
    role: 'Founding Vanguard Lead & Node Commander',
    bio: 'Direct coordinator for Effingham & regional NFC review beacons, express phone dispatch relays, and merchant onboarding. Reach out anytime at 508-507-0305 or frijj555@gmail.com.',
    town: 'Effingham, NH',
    rating: 5.0,
    reviewsCount: 156,
    avatar: '👑',
    badge: 'Founding Vanguard Lead',
    phone: '(508) 507-0305',
    email: 'frijj555@gmail.com',
    isVerified: true,
    totalProductsCount: 4,
    totalDeliveriesCompleted: 340,
    joinedDate: '2026-01-01',
  },
  {
    id: 'seller-walt',
    name: "Walt's Artisan Woodcraft",
    handle: '@walt_craft',
    role: 'Founding Carpenter & Maker',
    bio: 'Handcrafted hardwood boards, custom NFC tap pucks, and rustic furniture carved in Effingham, NH.',
    town: 'Effingham, NH',
    rating: 4.99,
    reviewsCount: 142,
    avatar: '🔨',
    badge: 'Founding Vanguard',
    phone: '(603) 555-0144',
    email: 'walt@example.com',
    isVerified: true,
    totalProductsCount: 6,
    totalDeliveriesCompleted: 184,
    joinedDate: '2026-01-15',
  },
  {
    id: 'seller-dave',
    name: 'Local Dave Courier Express',
    handle: '@dave_courier',
    role: 'Elite Deliverer & Fast Fleet',
    bio: 'Rapid local courier delivering artisan bakes, groceries, hot meals, and smart NFC hardware across Ossipee, Freedom, and Effingham.',
    town: 'Freedom, NH',
    rating: 5.0,
    reviewsCount: 310,
    avatar: '🚐',
    badge: 'Master Courier',
    phone: '(603) 555-0199',
    email: 'dave.courier@example.com',
    isVerified: true,
    totalProductsCount: 2,
    totalDeliveriesCompleted: 620,
    joinedDate: '2026-02-01',
  },
  {
    id: 'seller-sarah',
    name: 'Sarah NH Forage & Flora',
    handle: '@sarah_flora',
    role: 'Expansion Scout & Organic Herbalist',
    bio: 'Wild-harvested Chaga tea, local raw wildflower honey, and botanical tinctures sourced sustainably from Carroll County.',
    town: 'Ossipee, NH',
    rating: 4.97,
    reviewsCount: 98,
    avatar: '🌿',
    badge: 'Regional Scout',
    phone: '(603) 555-0812',
    email: 'sarah.nh@example.com',
    isVerified: true,
    totalProductsCount: 5,
    totalDeliveriesCompleted: 94,
    joinedDate: '2026-03-10',
  },
  {
    id: 'seller-oasis-bakery',
    name: 'Oasis Artisan Roastery & Bakehouse',
    handle: '@oasis_bakehouse',
    role: 'Craft Coffee & Stone Oven Bakery',
    bio: 'Small-batch single origin micro-roasts, stone oven sourdough bread, and fresh morning pastries delivered fresh daily.',
    town: 'Effingham, NH',
    rating: 4.98,
    reviewsCount: 428,
    avatar: '☕',
    badge: 'Oasis Flagship Node',
    phone: '(603) 555-0142',
    email: 'hello@oasiscoffee.com',
    isVerified: true,
    totalProductsCount: 8,
    totalDeliveriesCompleted: 450,
    joinedDate: '2026-01-01',
  },
];

export const INITIAL_SHOUTOUTS: ShoutoutPost[] = [
  {
    id: 'shout-1',
    authorName: 'Oasis Artisan Roastery',
    authorHandle: '@oasis_bakehouse',
    authorAvatar: '☕',
    authorBadge: 'Flagship Node',
    content: '🔥 Fresh morning sourdough just pulled from the hearth! Plus, our new tap-to-review NFC cards are now on all counter stations. Tap with your phone to get 10% off your cold brew!',
    tag: 'drop',
    reactions: {
      voltage: 24,
      fire: 38,
      heart: 19,
    },
    timestamp: '2026-09-14T16:15:00Z',
    sellerId: 'seller-oasis-bakery',
    town: 'Effingham, NH',
  },
  {
    id: 'shout-2',
    authorName: "Walt's Artisan Woodcraft",
    authorHandle: '@walt_craft',
    authorAvatar: '🔨',
    authorBadge: 'Founding Vanguard',
    content: '🌲 Finished 8 custom live-edge black walnut NFC tabletop tap blocks for local Effingham and Freedom businesses. Available for direct courier delivery today.',
    tag: 'drop',
    reactions: {
      voltage: 18,
      fire: 22,
      heart: 15,
    },
    timestamp: '2026-09-14T14:30:00Z',
    sellerId: 'seller-walt',
    town: 'Effingham, NH',
  },
  {
    id: 'shout-3',
    authorName: 'Local Dave Courier',
    authorHandle: '@dave_courier',
    authorAvatar: '🚐',
    authorBadge: 'Master Courier',
    content: '⚡ On road between Ossipee and Effingham. 15-minute dispatch available for all orders placed through the portal right now! Phone alerts armed and ready.',
    tag: 'courier',
    reactions: {
      voltage: 41,
      fire: 16,
      heart: 29,
    },
    timestamp: '2026-09-14T13:00:00Z',
    sellerId: 'seller-dave',
    town: 'Freedom, NH',
  },
  {
    id: 'shout-4',
    authorName: 'Elena Rostova',
    authorHandle: '@elena_patron',
    authorAvatar: '✨',
    content: '⭐ Just tapped the review card at Oasis Bakery after getting our cold brew. 1 tap and Google Review opened with 5 stars instantly! Super slick technology.',
    tag: 'review',
    reactions: {
      voltage: 30,
      fire: 12,
      heart: 45,
    },
    timestamp: '2026-09-14T11:45:00Z',
    town: 'Effingham, NH',
  },
];

export const INITIAL_PRODUCTS: ReviewProduct[] = [
  {
    id: 'prod-black-card',
    name: 'Stealth Obsidian NFC Review Card',
    slug: 'stealth-obsidian-card',
    subtitle: 'Ultra-durable Matte Black PVC with Dual NFC + QR',
    description: 'Our flagship smart card designed for servers, baristas, technicians, and cashiers. Tap directly to any modern smartphone (iPhone & Android) without needing any app.',
    price: 29.99,
    originalPrice: 49.99,
    rating: 4.98,
    reviewsCount: 342,
    badge: '★ Best Seller',
    category: 'cards',
    material: 'Matte Scratch-Resistant Obsidian PVC',
    colorOptions: ['#0f172a', '#1e1b4b', '#18181b', '#042f2e'],
    features: [
      'Instant Tap & Direct Review Prompt',
      'No App Required for Customers',
      'Unlimited Taps & Dynamic URL Changing',
      'Smart 5-Star Review Funnel Integration',
      'Waterproof, Bend-Resistant & UV-Protected'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-bamboo-card',
    name: 'Eco-Artisan Bamboo NFC Card',
    slug: 'eco-artisan-bamboo',
    subtitle: 'Sustainable Natural Wood with Embedded NFC Microchip',
    description: 'Laser-engraved eco-friendly bamboo card engineered for boutique cafes, organic spas, upscale salons, and sustainable retailers.',
    price: 34.99,
    originalPrice: 54.99,
    rating: 4.95,
    reviewsCount: 189,
    badge: 'Eco Edition',
    category: 'cards',
    material: '100% Genuine Sustainable Moso Bamboo',
    colorOptions: ['#b45309', '#78350f', '#451a03'],
    features: [
      'Warm Natural Wood Grain Aesthetic',
      'Laser-Precision Custom Logo Engraving',
      'Compatible with 99.9% of iOS & Android Devices',
      'Lifetime Cloud Destination Management'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-walt',
    sellerName: "Walt's Artisan Woodcraft",
    town: 'Effingham, NH',
  },
  {
    id: 'prod-acrylic-stand',
    name: 'Cyber Glass Countertop Tap Stand',
    slug: 'cyber-glass-stand',
    subtitle: 'Heavyweight Frosted Acrylic Tabletop Hub',
    description: 'Designed for high-traffic reception counters, checkout registers, and dining tables. Features a vibrant glowing Google Review banner and ultra-responsive NFC beacon.',
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.99,
    reviewsCount: 512,
    badge: 'Popular for Restaurants',
    category: 'stands',
    material: 'Architectural Grade 8mm Cast Acrylic',
    colorOptions: ['#4f46e5', '#f59e0b', '#10b981', '#ffffff'],
    features: [
      'Hands-Free Tap Angle for Smooth Customer Touch',
      'High-Resolution High-Contrast QR Code Backup',
      'Anti-Scratch Heavyweight Base with Non-Slip Rubber',
      'Multi-Location Fleet Management Included'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-tap-stickers-pack',
    name: 'Smart Vinyl NFC Review Stickers (Pack of 5)',
    slug: 'smart-nfc-stickers-5pack',
    subtitle: 'Industrial 3M Adhesive Weatherproof Tap Discs',
    description: 'Stick them on drive-thru windows, exit doors, menu boards, fleet vehicles, or counter glass. Tap anywhere to review.',
    price: 39.99,
    originalPrice: 65.00,
    rating: 4.92,
    reviewsCount: 220,
    badge: 'Value Pack',
    category: 'stickers',
    material: 'Heavy-Duty 3M Weatherproof Vinyl Disc',
    colorOptions: ['#000000', '#ffffff', '#2563eb'],
    features: [
      'Industrial Strength 3M Outdoor Adhesive',
      'Anti-Metal Shielding (Works on Metallic Surfaces)',
      'Weather, Sun, and Rain Resistant',
      'Independent URL/Card Routing per Sticker'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-dave',
    sellerName: 'Local Dave Courier',
    town: 'Freedom, NH',
  },
  {
    id: 'prod-hospitality-bundle',
    name: 'Enterprise Hospitality Commander Bundle',
    slug: 'hospitality-commander-bundle',
    subtitle: 'Complete Fleet: 2 Acrylic Stands + 5 Staff Cards + 10 Window Stickers',
    description: 'The ultimate Google 5-star domination toolkit for hotels, restaurants, automotive shops, and multi-location retail.',
    price: 149.99,
    originalPrice: 249.99,
    rating: 5.0,
    reviewsCount: 94,
    badge: 'Save 40%',
    category: 'bundles',
    material: 'Multi-Material Deluxe Package',
    colorOptions: ['#0f172a'],
    features: [
      '2x Cyber Glass Countertop Tap Stands',
      '5x Obsidian Staff Member NFC Cards',
      '10x Weatherproof NFC Door & Table Stickers',
      'Priority Cloud Analytics & VIP Staff Leaderboards'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557b6f7?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-walt-cutting-board',
    name: 'Live-Edge Walnut Tap Serving Board',
    slug: 'walt-walnut-serving-board',
    subtitle: 'Hand-Carved Black Walnut with Embedded Smart Review NFC',
    description: 'Solid New England black walnut serving platter featuring an embedded contactless NFC sensor on the corner handle. Ideal for tableside tasting flights and check presentation.',
    price: 74.99,
    originalPrice: 95.00,
    rating: 5.0,
    reviewsCount: 38,
    badge: 'Artisan Wood',
    category: 'artisan',
    material: 'Kiln-Dried Carroll County Black Walnut',
    features: [
      'Food-Safe Organic Beeswax & Mineral Oil Finish',
      'Invisible Embedded Waterproof NFC Beacon',
      'Custom Laser Brand Engraving on Request'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-walt',
    sellerName: "Walt's Artisan Woodcraft",
    town: 'Effingham, NH',
  },
  {
    id: 'prod-sarah-chaga-honey',
    name: 'Wild Chaga Infused Raw Wildflower Honey (16oz)',
    slug: 'sarah-chaga-honey',
    subtitle: 'Foraged in White Mountains & Cold-Filtered',
    description: 'Raw local honey infused with wild-foraged northern Chaga mushroom. Loaded with antioxidants and natural sweetness.',
    price: 22.00,
    originalPrice: 28.00,
    rating: 4.96,
    reviewsCount: 52,
    badge: 'Wild Harvest',
    category: 'food',
    features: [
      '100% Pure Raw Local Honey',
      'Wild White Mountains Chaga Infusion',
      'Hand Poured in Recycled Glass Jar'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-sarah',
    sellerName: 'Sarah NH Forage & Flora',
    town: 'Ossipee, NH',
  }
];

export const INITIAL_CARDS: NfcCardConfig[] = [
  {
    id: 'card-oasis-main',
    cardName: 'Main Counter Station 1',
    businessName: 'Oasis Coffee & Craft Bakery',
    googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    yelpUrl: 'https://yelp.com',
    tripAdvisorUrl: 'https://tripadvisor.com',
    mode: 'smart_funnel',
    thresholdStars: 4,
    customHeadline: 'How was your artisan experience today at Oasis?',
    logoUrl: '☕',
    primaryColor: '#f59e0b',
    assignedLocation: 'Effingham Main St',
    assignedStaff: 'Dave M.',
    active: true,
    totalTaps: 428,
    googleConversions: 379,
    privateFeedbacksCount: 22,
    createdAt: '2026-08-01T10:00:00Z',
    town: 'Effingham, NH'
  },
  {
    id: 'card-oasis-drive-thru',
    cardName: 'Drive-Thru Window Tap',
    businessName: 'Oasis Coffee & Craft Bakery',
    googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    mode: 'smart_funnel',
    thresholdStars: 4,
    customHeadline: 'Did our team brighten your drive today?',
    logoUrl: '🚗',
    primaryColor: '#4f46e5',
    assignedLocation: 'Effingham Main St',
    assignedStaff: 'Sarah K.',
    active: true,
    totalTaps: 312,
    googleConversions: 284,
    privateFeedbacksCount: 14,
    createdAt: '2026-08-10T14:30:00Z',
    town: 'Effingham, NH'
  },
  {
    id: 'card-demo-vip',
    cardName: 'VIP Direct Link Card',
    businessName: 'Apex Precision Automotive',
    googlePlaceId: 'ChIJL6Q0p_uuEmsR4063v1g7x90',
    googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    mode: 'direct_google',
    thresholdStars: 5,
    customHeadline: 'Leave us a review on Google!',
    logoUrl: '🏎️',
    primaryColor: '#10b981',
    assignedLocation: 'Bay 3',
    assignedStaff: 'Walt R.',
    active: true,
    totalTaps: 165,
    googleConversions: 165,
    privateFeedbacksCount: 0,
    createdAt: '2026-08-15T09:15:00Z',
    town: 'Conway, NH'
  }
];

export const INITIAL_TAP_LOGS: TapLog[] = [
  {
    id: 'tap-1',
    cardId: 'card-oasis-main',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-14T16:20:00Z',
    device: 'iOS',
    action: 'google_redirect',
    ratingSelected: 5,
    location: 'Effingham, NH'
  },
  {
    id: 'tap-2',
    cardId: 'card-oasis-main',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-14T15:45:00Z',
    device: 'Android',
    action: 'google_redirect',
    ratingSelected: 5,
    location: 'Ossipee, NH'
  },
  {
    id: 'tap-3',
    cardId: 'card-oasis-drive-thru',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-14T14:10:00Z',
    device: 'iOS',
    action: 'private_feedback',
    ratingSelected: 2,
    location: 'Freedom, NH'
  },
  {
    id: 'tap-4',
    cardId: 'card-demo-vip',
    businessName: 'Apex Precision Automotive',
    timestamp: '2026-09-14T13:05:00Z',
    device: 'iOS',
    action: 'direct_redirect',
    ratingSelected: 5,
    location: 'Conway, NH'
  },
  {
    id: 'tap-5',
    cardId: 'card-oasis-main',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-14T11:30:00Z',
    device: 'Android',
    action: 'google_redirect',
    ratingSelected: 4,
    location: 'Effingham, NH'
  }
];

export const INITIAL_FEEDBACKS: PrivateFeedback[] = [
  {
    id: 'fb-1',
    cardId: 'card-oasis-drive-thru',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-14T14:12:00Z',
    rating: 2,
    category: 'experience',
    customerName: 'Marcus V.',
    customerPhone: '(603) 555-0192',
    customerEmail: 'marcus.v@example.com',
    feedbackText: 'The cold brew was delicious but the drive-thru wait was over 12 minutes around 2 PM. Hope speed improves during rush hour!',
    status: 'new',
    town: 'Effingham, NH'
  },
  {
    id: 'fb-2',
    cardId: 'card-oasis-main',
    businessName: 'Oasis Coffee & Craft Bakery',
    timestamp: '2026-09-13T09:40:00Z',
    rating: 3,
    category: 'suggestion',
    customerName: 'Elena R.',
    customerEmail: 'elena.r@example.com',
    feedbackText: 'Great atmosphere, but music was a bit loud for remote work on laptop. Maybe lower volume in the morning?',
    status: 'in_progress',
    replyNote: 'Spoke with morning barista to keep acoustic playlist below 60dB.',
    town: 'Effingham, NH'
  },
  {
    id: 'fb-3',
    businessName: 'Local Dave Courier Express',
    timestamp: '2026-09-12T16:30:00Z',
    rating: 5,
    category: 'praise',
    customerName: 'Thomas K.',
    customerPhone: '(603) 555-0771',
    feedbackText: 'Dave delivered my woodcraft board in under 18 minutes! Absolute legend.',
    status: 'resolved',
    resolutionAction: 'Sent Thank You Note & $5 Referral Bonus Code',
    resolvedAt: '2026-09-12T17:00:00Z',
    town: 'Freedom, NH'
  }
];
