import { 
  ReviewProduct, NfcCardConfig, TapLog, PrivateFeedback, 
  SellerProfile, ShoutoutPost, TownNode, BeforeAfterShowcase, WorkRequest,
  NfcMenuProduct, NfcHardwareOrder
} from './types';

export const INITIAL_TOWNS: TownNode[] = [
  {
    id: 'town-effingham',
    name: 'Effingham',
    state: 'NH',
    fullName: 'Effingham, NH',
    tagline: 'North Gateway Hub',
    icon: '🏡',
    status: 'peak_flow',
    boutiquesCount: 4,
    routesCount: 12,
    occupancyLattice: 92,
    vanguardLead: 'Sean Martin',
    dispatchPhone: '(508) 507-0305',
    description: 'Premier independent discovery node with active sourdough bakehouses, woodcarvers, and high-frequency tap stations.',
    accentColor: '#f59e0b',
    joinedDate: '2026-01-01',
  },
  {
    id: 'town-freedom',
    name: 'Freedom',
    state: 'NH',
    fullName: 'Freedom, NH',
    tagline: 'Central Hub',
    icon: '🌳',
    status: 'stable',
    boutiquesCount: 2,
    routesCount: 4,
    occupancyLattice: 45,
    vanguardLead: 'Local Dave Courier',
    dispatchPhone: '(603) 555-0199',
    description: 'Central logistics waypoint providing rapid 15-minute courier runs and local artisan connections.',
    accentColor: '#6366f1',
    joinedDate: '2026-02-01',
  },
  {
    id: 'town-ossipee',
    name: 'Ossipee',
    state: 'NH',
    fullName: 'Ossipee, NH',
    tagline: 'Mountain Node',
    icon: '🏔️',
    status: 'stable',
    boutiquesCount: 2,
    routesCount: 8,
    occupancyLattice: 78,
    vanguardLead: 'Sarah NH Forage & Flora',
    dispatchPhone: '(603) 555-0812',
    description: 'Mountain valley hub specializing in wild foraged botanicals, raw honey, and wood-fired pizzerias.',
    accentColor: '#10b981',
    joinedDate: '2026-02-15',
  },
  {
    id: 'town-conway',
    name: 'Conway',
    state: 'NH',
    fullName: 'Conway, NH',
    tagline: 'Northern Apex Node',
    icon: '⚡',
    status: 'peak_flow',
    boutiquesCount: 3,
    routesCount: 6,
    occupancyLattice: 84,
    vanguardLead: 'Apex Precision Automotive',
    dispatchPhone: '(603) 555-0233',
    description: 'High-volume commercial node powering smart automotive services and high-traffic retail.',
    accentColor: '#3b82f6',
    joinedDate: '2026-03-01',
  },
];

export const INITIAL_SELLERS: SellerProfile[] = [
  {
    id: 'seller-sean',
    name: 'Sean Martin • Oasis Vanguard & Courier',
    handle: '@sean_vanguard',
    role: 'Founding Vanguard Lead & Regional Courier Dispatcher',
    bio: 'Direct coordinator for Carroll County & regional NFC review beacons, express custom errand runs, store pickups, and merchant onboarding. Phone: (508) 507-0305 | Email: frijj555@gmail.com.',
    town: 'Effingham, NH',
    rating: 5.0,
    reviewsCount: 156,
    avatar: '👑',
    badge: 'Founding Vanguard & Courier Lead',
    phone: '(508) 507-0305',
    email: 'frijj555@gmail.com',
    isVerified: true,
    totalProductsCount: 6,
    totalDeliveriesCompleted: 340,
    joinedDate: '2026-01-01',
  },
  {
    id: 'seller-pnb-eats',
    name: 'PNB Eats Roadside Grill',
    handle: '@pnb_eats',
    role: 'Effingham Roadside Diner & Pizzeria',
    bio: 'Hearty steak & cheese subs, stone-baked pizzas, crispy jumbo wings, and homemade maple fried dough on Route 25.',
    town: 'Effingham, NH',
    rating: 4.8,
    reviewsCount: 184,
    avatar: '🥪',
    badge: 'Verified Restaurant',
    phone: '(603) 539-7440',
    email: 'contact@pnbeats.com',
    isVerified: true,
    totalProductsCount: 5,
    totalDeliveriesCompleted: 210,
    joinedDate: '2026-01-15',
  },
  {
    id: 'seller-smoke-world',
    name: 'Smoke World Ossipee',
    handle: '@smoke_world_ossipee',
    role: 'Smoke, Vape & Borosilicate Glass Catalog',
    bio: 'Route 16 Ossipee premier smoke shop with Geek Bar disposables, 7mm borosilicate beaker bongs, vaporizers, torches, and rolling accessories.',
    town: 'Ossipee, NH',
    rating: 4.9,
    reviewsCount: 148,
    avatar: '💨',
    badge: 'Verified Merchant',
    phone: '(603) 539-7665',
    email: 'contact@smokeworldossipee.com',
    isVerified: true,
    totalProductsCount: 6,
    totalDeliveriesCompleted: 180,
    joinedDate: '2026-02-01',
  },
  {
    id: 'seller-yankee-smokehouse',
    name: 'Yankee Smokehouse BBQ',
    handle: '@yankee_smokehouse',
    role: 'Hardwood Applewood BBQ Smokehouse',
    bio: 'Slow-smoked St. Louis ribs, Carolina pulled pork, Texas brisket, and burnt ends mac & cheese at Jct Rte 16 & 25 in West Ossipee.',
    town: 'Ossipee, NH',
    rating: 4.7,
    reviewsCount: 1420,
    avatar: '🍖',
    badge: 'Verified Restaurant',
    phone: '(603) 539-2144',
    email: 'bbq@yankeesmokehouse.com',
    isVerified: true,
    totalProductsCount: 4,
    totalDeliveriesCompleted: 450,
    joinedDate: '2026-02-10',
  },
  {
    id: 'seller-hobbs-tavern',
    name: 'Hobbs Tavern & Brewing Co.',
    handle: '@hobbs_tavern',
    role: 'Craft Ales & Country Tavern Fare',
    bio: 'Fresh Hi-Fi Hazy NEIPA 4-packs, grass-fed bacon jam burgers, and wood-fired flatbreads brewed and cooked in West Ossipee.',
    town: 'Ossipee, NH',
    rating: 4.6,
    reviewsCount: 980,
    avatar: '🍺',
    badge: 'Verified Brewery & Tavern',
    phone: '(603) 539-2000',
    email: 'info@hobbstavern.com',
    isVerified: true,
    totalProductsCount: 4,
    totalDeliveriesCompleted: 390,
    joinedDate: '2026-02-15',
  },
  {
    id: 'seller-jakes-seafood',
    name: "Jake's Seafood & Grill",
    handle: '@jakes_seafood',
    role: 'Fresh Atlantic Lobster Rolls & Seafood Baskets',
    bio: 'Fresh cold/hot buttered Maine lobster rolls, whole belly Ipswich fried clams, and scratch New England clam chowder in Center Ossipee.',
    town: 'Ossipee, NH',
    rating: 4.5,
    reviewsCount: 650,
    avatar: '🦞',
    badge: 'Verified Restaurant',
    phone: '(603) 539-2805',
    email: 'orders@jakesseafoodnh.com',
    isVerified: true,
    totalProductsCount: 4,
    totalDeliveriesCompleted: 280,
    joinedDate: '2026-02-20',
  }
];

export const INITIAL_SHOUTOUTS: ShoutoutPost[] = [
  {
    id: 'shout-1',
    authorName: 'Sean Martin • Oasis Vanguard',
    authorHandle: '@sean_vanguard',
    authorAvatar: '👑',
    authorBadge: 'Founding Vanguard',
    content: '🚀 OasisTap Town Nodes & Courier Dispatch are officially live across Effingham, Ossipee, Freedom, Wakefield, and Conway! Need anything picked up or delivered from local stores? Prepay via Cash App, Venmo, Zelle or Card and I will deliver it straight to your door.',
    tag: 'courier',
    reactions: {
      voltage: 34,
      fire: 42,
      heart: 28,
    },
    timestamp: new Date().toISOString(),
    sellerId: 'seller-sean',
    town: 'Effingham, NH',
  },
  {
    id: 'shout-2',
    authorName: 'Smoke World Ossipee',
    authorHandle: '@smoke_world_ossipee',
    authorAvatar: '💨',
    authorBadge: 'Verified Merchant',
    content: '⚡ Full catalog of Geek Bar Pulse 15k disposables, handblown 7mm borosilicate glass bongs, Lookah vaporizers, and raw papers are now available for local courier pickup and delivery!',
    tag: 'drop',
    reactions: {
      voltage: 22,
      fire: 29,
      heart: 18,
    },
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    sellerId: 'seller-smoke-world',
    town: 'Ossipee, NH',
  }
];

export const INITIAL_PRODUCTS: ReviewProduct[] = [
  {
    id: 'prod-black-card',
    name: 'Stealth Obsidian NFC Review Card',
    slug: 'stealth-obsidian-card',
    subtitle: 'Ultra-durable Matte Black PVC with Dual NFC + QR',
    description: 'Our flagship smart card designed for servers, baristas, technicians, and cashiers. Tap directly to any modern smartphone (iPhone & Android) without needing any app.',
    price: 29.99,
    originalPrice: 49.99,
    rating: 4.98,
    reviewsCount: 342,
    badge: '★ Best Seller',
    category: 'cards',
    material: 'Matte Scratch-Resistant Obsidian PVC',
    colorOptions: ['#0f172a', '#1e1b4b', '#18181b', '#042f2e'],
    features: [
      'Instant Tap & Direct Review Prompt',
      'No App Required for Customers',
      'Unlimited Taps & Dynamic URL Changing',
      'Smart 5-Star Review Funnel Integration',
      'Waterproof, Bend-Resistant & UV-Protected'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-bamboo-card',
    name: 'Eco-Artisan Bamboo NFC Card',
    slug: 'eco-artisan-bamboo',
    subtitle: 'Sustainable Natural Wood with Embedded NFC Microchip',
    description: 'Laser-engraved eco-friendly bamboo card engineered for boutique cafes, organic spas, upscale salons, and sustainable retailers.',
    price: 34.99,
    originalPrice: 54.99,
    rating: 4.95,
    reviewsCount: 189,
    badge: 'Eco Edition',
    category: 'cards',
    material: '100% Genuine Sustainable Moso Bamboo',
    colorOptions: ['#b45309', '#78350f', '#451a03'],
    features: [
      'Warm Natural Wood Grain Aesthetic',
      'Laser-Precision Custom Logo Engraving',
      'Compatible with 99.9% of iOS & Android Devices',
      'Lifetime Cloud Destination Management'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-walt',
    sellerName: "Walt's Artisan Woodcraft",
    town: 'Effingham, NH',
  },
  {
    id: 'prod-acrylic-stand',
    name: 'Cyber Glass Countertop Tap Stand',
    slug: 'cyber-glass-stand',
    subtitle: 'Heavyweight Frosted Acrylic Tabletop Hub',
    description: 'Designed for high-traffic reception counters, checkout registers, and dining tables. Features a vibrant glowing Google Review banner and ultra-responsive NFC beacon.',
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.99,
    reviewsCount: 512,
    badge: 'Popular for Restaurants',
    category: 'stands',
    material: 'Architectural Grade 8mm Cast Acrylic',
    colorOptions: ['#4f46e5', '#f59e0b', '#10b981', '#ffffff'],
    features: [
      'Hands-Free Tap Angle for Smooth Customer Touch',
      'High-Resolution High-Contrast QR Code Backup',
      'Anti-Scratch Heavyweight Base with Non-Slip Rubber',
      'Multi-Location Fleet Management Included'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-tap-stickers-pack',
    name: 'Smart Vinyl NFC Review Stickers (Pack of 5)',
    slug: 'smart-nfc-stickers-5pack',
    subtitle: 'Industrial 3M Adhesive Weatherproof Tap Discs',
    description: 'Stick them on drive-thru windows, exit doors, menu boards, fleet vehicles, or counter glass. Tap anywhere to review.',
    price: 39.99,
    originalPrice: 65.00,
    rating: 4.92,
    reviewsCount: 220,
    badge: 'Value Pack',
    category: 'stickers',
    material: 'Heavy-Duty 3M Weatherproof Vinyl Disc',
    colorOptions: ['#000000', '#ffffff', '#2563eb'],
    features: [
      'Industrial Strength 3M Outdoor Adhesive',
      'Anti-Metal Shielding (Works on Metallic Surfaces)',
      'Weather, Sun, and Rain Resistant',
      'Independent URL/Card Routing per Sticker'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-dave',
    sellerName: 'Local Dave Courier',
    town: 'Freedom, NH',
  },
  {
    id: 'prod-hospitality-bundle',
    name: 'Enterprise Hospitality Commander Bundle',
    slug: 'hospitality-commander-bundle',
    subtitle: 'Complete Fleet: 2 Acrylic Stands + 5 Staff Cards + 10 Window Stickers',
    description: 'The ultimate Google 5-star domination toolkit for hotels, restaurants, automotive shops, and multi-location retail.',
    price: 149.99,
    originalPrice: 249.99,
    rating: 5.0,
    reviewsCount: 94,
    badge: 'Save 40%',
    category: 'bundles',
    material: 'Multi-Material Deluxe Package',
    colorOptions: ['#0f172a'],
    features: [
      '2x Cyber Glass Countertop Tap Stands',
      '5x Obsidian Staff Member NFC Cards',
      '10x Weatherproof NFC Door & Table Stickers',
      'Priority Cloud Analytics & VIP Staff Leaderboards'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557b6f7?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    isBestSeller: true,
    sellerId: 'seller-oasis-bakery',
    sellerName: 'Oasis Flagship Node',
    town: 'Effingham, NH',
  },
  {
    id: 'prod-walt-cutting-board',
    name: 'Live-Edge Walnut Tap Serving Board',
    slug: 'walt-walnut-serving-board',
    subtitle: 'Hand-Carved Black Walnut with Embedded Smart Review NFC',
    description: 'Solid New England black walnut serving platter featuring an embedded contactless NFC sensor on the corner handle. Ideal for tableside tasting flights and check presentation.',
    price: 74.99,
    originalPrice: 95.00,
    rating: 5.0,
    reviewsCount: 38,
    badge: 'Artisan Wood',
    category: 'artisan',
    material: 'Kiln-Dried Carroll County Black Walnut',
    features: [
      'Food-Safe Organic Beeswax & Mineral Oil Finish',
      'Invisible Embedded Waterproof NFC Beacon',
      'Custom Laser Brand Engraving on Request'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-walt',
    sellerName: "Walt's Artisan Woodcraft",
    town: 'Effingham, NH',
  },
  {
    id: 'prod-sarah-chaga-honey',
    name: 'Wild Chaga Infused Raw Wildflower Honey (16oz)',
    slug: 'sarah-chaga-honey',
    subtitle: 'Foraged in White Mountains & Cold-Filtered',
    description: 'Raw local honey infused with wild-foraged northern Chaga mushroom. Loaded with antioxidants and natural sweetness.',
    price: 22.00,
    originalPrice: 28.00,
    rating: 4.96,
    reviewsCount: 52,
    badge: 'Wild Harvest',
    category: 'food',
    features: [
      '100% Pure Raw Local Honey',
      'Wild White Mountains Chaga Infusion',
      'Hand Poured in Recycled Glass Jar'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    sellerId: 'seller-sarah',
    sellerName: 'Sarah NH Forage & Flora',
    town: 'Ossipee, NH',
  }
];

export const INITIAL_CARDS: NfcCardConfig[] = [
  {
    id: 'card-oasis-main',
    cardName: 'Main Counter Station 1',
    businessName: 'Oasis Coffee & Craft Bakery',
    googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
    googleReviewUrl: 'https://www.google.com/search?q=Oasis+Coffee+Bakery+Effingham+NH',
    yelpUrl: 'https://yelp.com',
    tripAdvisorUrl: 'https://tripadvisor.com',
    mode: 'smart_funnel',
    thresholdStars: 4,
    customHeadline: 'How was your artisan experience today at Oasis?',
    logoUrl: '☕',
    primaryColor: '#f59e0b',
    assignedLocation: 'Effingham Main St',
    assignedStaff: 'Dave M.',
    active: true,
    totalTaps: 428,
    googleConversions: 379,
    privateFeedbacksCount: 22,
    createdAt: '2026-08-01T10:00:00Z',
    town: 'Effingham, NH'
  },
  {
    id: 'card-oasis-drive-thru',
    cardName: 'Drive-Thru Window Tap',
    businessName: 'Oasis Coffee & Craft Bakery',
    googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
    googleReviewUrl: 'https://www.google.com/search?q=Oasis+Coffee+Bakery+Effingham+NH',
    mode: 'smart_funnel',
    thresholdStars: 4,
    customHeadline: 'Did our team brighten your drive today?',
    logoUrl: '🚗',
    primaryColor: '#4f46e5',
    assignedLocation: 'Effingham Main St',
    assignedStaff: 'Sarah K.',
    active: true,
    totalTaps: 312,
    googleConversions: 284,
    privateFeedbacksCount: 14,
    createdAt: '2026-08-10T14:30:00Z',
    town: 'Effingham, NH'
  },
  {
    id: 'card-demo-vip',
    cardName: 'VIP Direct Link Card',
    businessName: 'Apex Precision Automotive',
    googlePlaceId: 'ChIJL6Q0p_uuEmsR4063v1g7x90',
    googleReviewUrl: 'https://www.google.com/search?q=Apex+Precision+Automotive+NH',
    mode: 'direct_google',
    thresholdStars: 5,
    customHeadline: 'Leave us a review on Google!',
    logoUrl: '🏎️',
    primaryColor: '#10b981',
    assignedLocation: 'Bay 3',
    assignedStaff: 'Walt R.',
    active: true,
    totalTaps: 165,
    googleConversions: 165,
    privateFeedbacksCount: 0,
    createdAt: '2026-08-15T09:15:00Z',
    town: 'Conway, NH'
  }
];

export const INITIAL_TAP_LOGS: TapLog[] = [];

export const INITIAL_FEEDBACKS: PrivateFeedback[] = [];

export const INITIAL_BEFORE_AFTER_SHOWCASES: BeforeAfterShowcase[] = [
  {
    id: 'showcase-1',
    businessName: 'Carroll County Custom Decks & Carpentry',
    businessCategory: 'carpentry',
    projectTitle: 'Ossipee Lake Weathered Deck Teardown & Cedar Timber Rebuild',
    description: 'Complete removal of 20-year-old rotting pine decking. Rebuilt with premium western red cedar, concealed fasteners, custom steps, and matte black stainless cable railings with panoramic lake views.',
    town: 'Center Ossipee',
    state: 'NH',
    beforeImageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    beforeCaption: 'Rotting 20-year pine boards & unstable balusters',
    afterCaption: 'Handcrafted Red Cedar Timber Deck with Cable Railings',
    costOrBudgetEstimate: '$6,800 - $8,500',
    timeToComplete: '4 Days',
    contactPhone: '(603) 539-8100',
    contactEmail: 'decks@carrollcountycarpentry.com',
    websiteUrl: 'https://carrollcountycarpentry.com',
    googleReviewUrl: 'https://google.com',
    rating: 4.9,
    specialOffer: '★ 10% Off Spring & Summer Deck Builds booked this month!',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    featured: true,
    likesCount: 38,
    userLiked: false,
  },
  {
    id: 'showcase-2',
    businessName: 'White Mountain Tree Care & Land Clearing',
    businessCategory: 'tree_service',
    projectTitle: 'Hazardous Leaning Storm Pine Removal & Driveway Clearing',
    description: 'Safely rigged and dismantled two 80-foot dead white pines leaning over the customer driveway and power drop. Stump grinded and stacked 3 cords of clean hardwood firewood.',
    town: 'Effingham',
    state: 'NH',
    beforeImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    beforeCaption: 'Hazardous 80ft storm-cracked pine threatening home',
    afterCaption: 'Clean sunny cleared driveway with seasoned firewood stacked',
    costOrBudgetEstimate: '$1,800',
    timeToComplete: '1 Day',
    contactPhone: '(603) 539-4400',
    contactEmail: 'trees@whitemountaincare.com',
    rating: 5.0,
    specialOffer: '★ Free On-Site Hazardous Tree & Firewood Assessment',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    featured: true,
    likesCount: 29,
    userLiked: true,
  },
  {
    id: 'showcase-3',
    businessName: 'Lakes Region Pro Stonework & Hardscaping',
    businessCategory: 'landscaping',
    projectTitle: 'Eroded Muddy Hillside to Handcrafted Granite Firepit Patio',
    description: 'Transformed washed-out muddy slope into a 2-tier native New Hampshire granite retaining wall with thermal bluestone pavers, outdoor wood-burning firepit, and low-voltage warm LED lighting.',
    town: 'Wolfeboro',
    state: 'NH',
    beforeImageUrl: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?w=800&auto=format&fit=crop&q=80',
    beforeCaption: 'Washed out muddy hill with poor water drainage',
    afterCaption: 'Bluestone Paver Patio with Granite Firepit & Ambient Lighting',
    costOrBudgetEstimate: '$4,200',
    timeToComplete: '3 Days',
    contactPhone: '(603) 569-7200',
    rating: 4.95,
    specialOffer: '★ $250 Off Any Hardscape Project over $3,000',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    featured: true,
    likesCount: 45,
    userLiked: false,
  },
  {
    id: 'showcase-4',
    businessName: 'Heritage New England Historic Painting & Siding',
    businessCategory: 'painting',
    projectTitle: '1890s Historic Farmhouse Peeling Exterior Restoration',
    description: 'Complete lead-safe pressure wash, scraping, oil primer sealing, and 2-coat Benjamin Moore exterior satin acrylic finish in Cape Cod Gray with Crisp White architectural trim.',
    town: 'Freedom',
    state: 'NH',
    beforeImageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&auto=format&fit=crop&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&auto=format&fit=crop&q=80',
    beforeCaption: 'Peeling weathered cedar siding with moisture damage',
    afterCaption: 'Restored Historic Farmhouse in Cape Cod Gray & White Trim',
    costOrBudgetEstimate: '$5,400',
    timeToComplete: '5 Days',
    contactPhone: '(603) 539-3300',
    rating: 4.88,
    specialOffer: '★ Free Powerwash with any Full Exterior Paint Contract',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    featured: false,
    likesCount: 21,
    userLiked: false,
  }
];

export const INITIAL_WORK_REQUESTS: WorkRequest[] = [
  {
    id: 'req-1',
    title: 'Spring Yard Cleanup, Fallen Branch Clearing & Firewood Stacking',
    category: 'landscaping',
    description: 'Looking for a reliable local contractor or helper with a trailer or truck to clear winter branch fall, rake perimeter lawn, and stack 2 cords of split firewood by shed.',
    town: 'Effingham',
    state: 'NH',
    budgetRange: '$200 - $500',
    urgency: 'within_few_days',
    requesterName: 'Tom Henderson',
    requesterPhone: '(603) 539-9921',
    addressOrNeighborhood: 'Snows Mountain Rd, Effingham',
    beforeImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80',
    status: 'open',
    quotesCount: 2,
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'req-2',
    title: 'Rebuild 4 Weathered Front Entry Steps & Replace Handrail',
    category: 'carpentry',
    description: 'Pressure treated front entryway stairs are cracked and wobbly. Need 4 new 48" stringers, tread boards, and sturdy wooden handrail installed before summer guests arrive.',
    town: 'Freedom',
    state: 'NH',
    budgetRange: '$500 - $1,500',
    urgency: 'within_few_days',
    requesterName: 'Carol Vance',
    requesterPhone: '(603) 539-1144',
    addressOrNeighborhood: 'Ossipee Lake Shoreline, Freedom',
    beforeImageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=600&auto=format&fit=crop&q=80',
    status: 'open',
    quotesCount: 1,
    createdAt: new Date(Date.now() - 14 * 3600000).toISOString(),
  },
  {
    id: 'req-3',
    title: 'Gravel Driveway Grading & Drainage Washout Fix',
    category: 'masonry',
    description: 'Spring runoff created a rut down our 200ft gravel driveway. Need tractor grading, 2 loads of crushed bank-run gravel spread and compacted.',
    town: 'Center Ossipee',
    state: 'NH',
    budgetRange: '$500 - $1,500',
    urgency: 'flexible_this_month',
    requesterName: 'Mark Albright',
    requesterPhone: '(603) 539-5588',
    addressOrNeighborhood: 'Route 16 Corridor, Center Ossipee',
    status: 'open',
    quotesCount: 3,
    createdAt: new Date(Date.now() - 28 * 3600000).toISOString(),
  },
  {
    id: 'req-4',
    title: 'Interior Living Room & High Ceiling Stairwell Painting',
    category: 'painting',
    description: 'Cathedral ceiling living room and stairwell wall repainting in neutral warm white. Approximately 600 sq ft of wall space. Paint provided or can be budgeted.',
    town: 'Wolfeboro',
    state: 'NH',
    budgetRange: '$1,500 - $5,000',
    urgency: 'flexible_this_month',
    requesterName: 'Janet Miller',
    requesterPhone: '(603) 569-4411',
    addressOrNeighborhood: 'South Main St, Wolfeboro',
    status: 'open',
    quotesCount: 2,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  }
];

export const INITIAL_NFC_MENU_PRODUCTS: NfcMenuProduct[] = [
  {
    id: 'nfc-menu-acrylic-stand',
    title: 'Dual-Sided Acrylic Tap-to-Order Table Stand (Pre-Encoded)',
    subtitle: 'Commercial High-Gain NTAG215 Table Stand with Direct Menu Link',
    description: 'Commercial restaurant table stand pre-programmed with your live online digital menu. Customers tap their iPhone or Android phone to instantly open your food and drinks ordering page.',
    targetRestaurantSlug: 'pnb-eats',
    targetRestaurantName: 'PNB Eats Roadside Grill',
    menuUrl: 'https://oasistap.com/site/pnb-eats',
    tableNumber: 'Table #1',
    formFactor: 'acrylic_table_stand',
    chipType: 'NTAG215',
    price: 24.99,
    originalPrice: 39.99,
    inventoryCount: 38,
    unitsSold: 54,
    badge: '★ Best for Diners & Cafes',
    coverImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    accentColor: '#f59e0b',
    isPublished: true,
    features: [
      'Pre-encoded with live digital menu URL',
      'High-Density NTAG215 NFC Microchip (504 bytes)',
      'Laser-sharp scratchproof table QR code backing',
      'Commercial UV-resistant clear acrylic',
      'No app download needed for diners'
    ],
    dimensions: '4" x 6" Free-Standing Base',
    material: 'Shatterproof Acrylic',
    includesStandTent: true,
    createdAt: '2026-08-01T10:00:00Z'
  },
  {
    id: 'nfc-menu-table-disc',
    title: 'Commercial Self-Adhesive PVC Table Tap Disc (35mm)',
    subtitle: 'Ultra-Slim Waterproof 3M Sticky Disc with Embedded NTAG213',
    description: 'Flush-mount disc engineered to stick directly to dining tables, high-top bar surfaces, or outdoor patio picnic tables. Pre-programmed with digital menu for tap-to-order.',
    targetRestaurantSlug: 'pizza-barn-smokehouse',
    targetRestaurantName: 'Pizza Barn & Smokehouse',
    menuUrl: 'https://oasistap.com/site/pizza-barn-smokehouse',
    formFactor: 'pvc_table_disc',
    chipType: 'NTAG213',
    price: 12.50,
    originalPrice: 18.00,
    inventoryCount: 120,
    unitsSold: 88,
    badge: 'Patio & Bar Favorite',
    coverImageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    accentColor: '#ef4444',
    isPublished: true,
    features: [
      'Industrial 3M self-adhesive backing',
      'IP68 waterproof & alcohol-cleaner resistant',
      'Sub-1mm ultra-slim low profile',
      'Pre-flashed with live menu destination'
    ],
    dimensions: '35mm Diameter (1.37")',
    material: 'Matte PVC + 3M VHB',
    createdAt: '2026-08-10T12:00:00Z'
  },
  {
    id: 'nfc-menu-wood-tent',
    title: 'Rustic Artisan Hardwood NFC Table Tent',
    subtitle: 'Handcrafted New England Sugar Maple with Concealed NFC Chip',
    description: 'Custom laser-engraved wood table tent with hidden NFC antenna and carved QR emblem. Built for craft taprooms, taverns, and farm-to-table eateries.',
    targetRestaurantSlug: 'hobbs-tavern-brewing',
    targetRestaurantName: 'Hobbs Tavern & Brewing Co.',
    menuUrl: 'https://oasistap.com/site/hobbs-tavern-brewing',
    formFactor: 'wood_table_tent',
    chipType: 'NTAG216',
    price: 29.99,
    originalPrice: 45.00,
    inventoryCount: 22,
    unitsSold: 34,
    badge: 'Artisan Hardwood',
    coverImageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    accentColor: '#f59e0b',
    isPublished: true,
    features: [
      '100% Solid New Hampshire Hardwood',
      'Laser-engraved restaurant logo & table number',
      'High-memory NTAG216 NFC chip (888 bytes)',
      'Hand-rubbed natural beeswax finish'
    ],
    dimensions: '3.5" x 5" Double-Sided A-Frame',
    material: 'Solid Maple & Walnut',
    includesStandTent: true,
    createdAt: '2026-08-15T14:00:00Z'
  },
  {
    id: 'nfc-menu-server-badge',
    title: 'Waitstaff & Bartender Instant Tap Wearable Badge',
    subtitle: 'Magnetic Clip Wearable Smart Badge for Servers & Bartenders',
    description: 'Staff wearable smart card allowing waitstaff and bartenders to offer diners a 1-second phone tap on their uniform to pull up menus or tip.',
    targetRestaurantSlug: 'jakes-seafood-grill',
    targetRestaurantName: "Jake's Seafood & Grill",
    menuUrl: 'https://oasistap.com/site/jakes-seafood-grill',
    formFactor: 'waitstaff_badge',
    chipType: 'NTAG213',
    price: 19.99,
    originalPrice: 29.99,
    inventoryCount: 45,
    unitsSold: 62,
    badge: 'Staff Essential',
    coverImageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    accentColor: '#06b6d4',
    isPublished: true,
    features: [
      'Heavy-duty dual neodymium magnet clothing clip',
      'Instant tap on server lapel/apron',
      'Connects to digital menu + staff tip jar',
      'Durable scratch-resistant gloss laminate'
    ],
    dimensions: '3.375" x 2.125" Standard CR80 Badge',
    material: 'Polycarbonate Composite',
    createdAt: '2026-08-20T16:00:00Z'
  },
  {
    id: 'nfc-menu-drive-thru',
    title: 'All-Weather Curbside & Drive-Thru High-Gain NFC Post Tag',
    subtitle: 'Heavy-Duty IP68 Outdoor Tag with 50mm Long-Range Antenna',
    description: 'Heavy-duty weatherproof tag mounted at Hannaford To Go curbside pickup bays and drive-thru lanes for instant mobile order check-in.',
    targetRestaurantSlug: 'hannaford-to-go',
    targetRestaurantName: 'Hannaford Supermarket & Hannaford To Go',
    menuUrl: 'https://oasistap.com/site/hannaford-to-go',
    formFactor: 'outdoor_drive_thru',
    chipType: 'NTAG215',
    price: 34.99,
    originalPrice: 49.99,
    inventoryCount: 18,
    unitsSold: 26,
    badge: 'Weatherproof IP68',
    coverImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    accentColor: '#16a34a',
    isPublished: true,
    features: [
      'Rated for -30°F to +140°F New England weather',
      'High-gain 50mm antenna reads through vehicle glass',
      'Vandal-resistant ABS casing with screw holes',
      'Pre-programmed with curbside arrival portal'
    ],
    dimensions: '60mm x 60mm Tough Casing',
    material: 'Ruggedized Industrial ABS',
    createdAt: '2026-08-25T11:00:00Z'
  },
  {
    id: 'nfc-menu-keychain-tag',
    title: 'VIP Regular Patron Fast-Reorder NFC Keychain',
    subtitle: 'Leatherette & Brushed Alloy Smart FOB with Instant Food Re-Order',
    description: 'Pocket-sized luxury keychain tag given to regular patrons and seasonal cabin owners. Tap anytime from their couch to instantly open restaurant delivery checkout.',
    targetRestaurantSlug: 'freedom-village-store',
    targetRestaurantName: 'Freedom Village Store & Cafe',
    menuUrl: 'https://oasistap.com/site/freedom-village-store',
    formFactor: 'keychain_tag',
    chipType: 'NTAG213',
    price: 9.99,
    originalPrice: 15.00,
    inventoryCount: 75,
    unitsSold: 110,
    badge: 'VIP Re-Order',
    coverImageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
    accentColor: '#10b981',
    isPublished: true,
    features: [
      'Brushed zinc alloy ring with stitched leatherette',
      'Instant tap to re-order favorite morning coffee & scones',
      'Built-in VIP customer loyalty discount',
      'Water-resistant & drop-proof'
    ],
    dimensions: '45mm x 30mm FOB',
    material: 'Zinc Alloy & Vegan Leatherette',
    createdAt: '2026-08-30T09:00:00Z'
  }
];

export const INITIAL_NFC_HARDWARE_ORDERS: NfcHardwareOrder[] = [
  {
    id: 'hord-101',
    orderNumber: 'NFC-8041',
    buyerName: 'Gary Collins (Owner)',
    buyerPhone: '(603) 539-7440',
    buyerEmail: 'gary@pnbeats.com',
    buyerBusinessName: 'PNB Eats Roadside Grill',
    deliveryAddress: 'NH-25, Effingham, NH 03882',
    productId: 'nfc-menu-acrylic-stand',
    productTitle: 'Dual-Sided Acrylic Tap-to-Order Table Stand (Pre-Encoded)',
    formFactor: 'acrylic_table_stand',
    targetRestaurantName: 'PNB Eats Roadside Grill',
    quantity: 8,
    unitPrice: 24.99,
    totalAmount: 199.92,
    status: 'delivered',
    programmedUrl: 'https://oasistap.com/site/pnb-eats',
    tableAssignments: ['Table 1', 'Table 2', 'Table 3', 'Table 4', 'Table 5', 'Table 6', 'Bar A', 'Bar B'],
    chipType: 'NTAG215',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    paidStatus: 'paid'
  },
  {
    id: 'hord-102',
    orderNumber: 'NFC-8042',
    buyerName: 'Dan Sullivan',
    buyerPhone: '(603) 539-2244',
    buyerBusinessName: 'Pizza Barn & Smokehouse',
    deliveryAddress: 'Route 16, Center Ossipee, NH 03814',
    productId: 'nfc-menu-table-disc',
    productTitle: 'Commercial Self-Adhesive PVC Table Tap Disc (35mm)',
    formFactor: 'pvc_table_disc',
    targetRestaurantName: 'Pizza Barn & Smokehouse',
    quantity: 12,
    unitPrice: 12.50,
    totalAmount: 150.00,
    status: 'programmed_qa',
    programmedUrl: 'https://oasistap.com/site/pizza-barn-smokehouse',
    tableAssignments: ['Patio 1', 'Patio 2', 'Patio 3', 'Patio 4', 'Dining 1', 'Dining 2'],
    chipType: 'NTAG213',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    paidStatus: 'paid'
  },
  {
    id: 'hord-103',
    orderNumber: 'NFC-8043',
    buyerName: 'Mike Hobbs',
    buyerPhone: '(603) 539-2000',
    buyerBusinessName: 'Hobbs Tavern & Brewing Co.',
    deliveryAddress: '2415 White Mountain Hwy, West Ossipee, NH 03890',
    productId: 'nfc-menu-wood-tent',
    productTitle: 'Rustic Artisan Hardwood NFC Table Tent',
    formFactor: 'wood_table_tent',
    targetRestaurantName: 'Hobbs Tavern & Brewing Co.',
    quantity: 6,
    unitPrice: 29.99,
    totalAmount: 179.94,
    status: 'pending_flash',
    programmedUrl: 'https://oasistap.com/site/hobbs-tavern-brewing',
    tableAssignments: ['Taproom 1', 'Taproom 2', 'Taproom 3', 'Taproom 4', 'Beer Garden 1', 'Beer Garden 2'],
    chipType: 'NTAG216',
    createdAt: new Date().toISOString(),
    paidStatus: 'pay_on_delivery'
  }
];



