import { 
  TreasureMilestoneReward, 
  SocietyMemberProfile, 
  SocietyCommunityBounty, 
  SocietyCipherRiddle 
} from './types';

export const INITIAL_TREASURE_MILESTONES: TreasureMilestoneReward[] = [
  {
    id: 'milestone-bronze-3',
    requiredCheckpoints: 3,
    tier: 'bronze',
    title: 'Bronze Explorer Vault',
    description: 'Claim your first 3 real-world NFC checkpoints across Carroll County trails & stores.',
    rewardType: 'voucher',
    rewardValue: '15% Off Any Local Dining or Bakery Order',
    rewardCode: 'BRONZE-SCOUT-15',
    iconEmoji: '🥉',
  },
  {
    id: 'milestone-silver-6',
    requiredCheckpoints: 6,
    tier: 'silver',
    title: 'Silver Trailmaster Chest',
    description: 'Explore 6 checkpoints spanning historic landmarks, artisan shops, and lake lookouts.',
    rewardType: 'voucher',
    rewardValue: 'Free Hearth Artisan Sourdough Loaf or Maple Cinnamon Roll 4-Pack',
    rewardCode: 'SILVER-TRAIL-BAKE',
    iconEmoji: '🥈',
  },
  {
    id: 'milestone-gold-10',
    requiredCheckpoints: 10,
    tier: 'gold',
    title: 'Gold Vanguard Treasure Vault',
    description: 'Complete 10 checkpoint taps across Effingham, Ossipee, Freedom, and Conway.',
    rewardType: 'physical_fob',
    rewardValue: '$25 Carroll County Local Credit + Custom NFC VIP Keychain FOB (Hand-Delivered by Sean Martin)',
    rewardCode: 'GOLD-VANGUARD-25',
    iconEmoji: '🥇',
  },
  {
    id: 'milestone-sovereign-15',
    requiredCheckpoints: 15,
    tier: 'master_sovereign',
    title: 'Grand Sovereign Order Relic',
    description: 'Master all trails, solve every cryptic cipher, and complete the full Carroll County circuit.',
    rewardType: 'society_relic',
    rewardValue: '$100 Master Bounty Credit + Grand Sovereign Gold Pass + Induction into Townraise Hall of Fame',
    rewardCode: 'SOVEREIGN-ORDER-100',
    iconEmoji: '💎',
  }
];

export const INITIAL_SOCIETY_BOUNTIES: SocietyCommunityBounty[] = [
  {
    id: 'bounty-100-taps-coop',
    title: 'Carroll County 100-Tap Community Cooperative',
    category: 'community_coop',
    description: 'Collective society mission: When citizens log 100 total checkpoint taps across all towns, Free Courier Delivery unlocks for everyone this weekend!',
    targetCount: 100,
    currentProgress: 0,
    rewardSummary: 'Free Courier Delivery across Carroll County for all diners & residents',
    expiresIn: '3 Days Remaining',
    iconEmoji: '🌲',
    isCompleted: false,
  },
  {
    id: 'bounty-railroad-cipher',
    title: 'The 1870 Boston & Maine Telegraph Cipher',
    category: 'secret_cipher',
    description: 'Decode the secret Morse riddle hidden near the Center Ossipee train depot marker.',
    targetCount: 1,
    currentProgress: 0,
    rewardSummary: '300 Society XP + Free Smokehouse Cornbread Voucher',
    expiresIn: 'Active Weekly Quest',
    iconEmoji: '🚂',
    isCompleted: false,
  },
  {
    id: 'bounty-morning-bakers',
    title: 'Morning Artisan Coffee & Bakehouse Crawl',
    category: 'artisan_patron',
    description: 'Check in at 3 participating bakery and cafe beacons before 12:00 PM.',
    targetCount: 3,
    currentProgress: 0,
    rewardSummary: '200 Society XP + $5 Coffee Bounty Credit',
    expiresIn: 'Daily Morning Reset',
    iconEmoji: '☕',
    isCompleted: false,
  },
  {
    id: 'bounty-lake-scout',
    title: 'Broad Bay Lakehouse Secret Beacon Hunt',
    category: 'speedrun',
    description: 'Locate the hidden weather-resistant NFC disc mounted along the public shoreline trail.',
    targetCount: 1,
    currentProgress: 0,
    rewardSummary: '250 Society XP + 15% Off Boat/Kayak Rentals',
    expiresIn: 'Active Season Quest',
    iconEmoji: '🌊',
    isCompleted: false,
  }
];

export const INITIAL_CIPHER_RIDDLES: SocietyCipherRiddle[] = [
  {
    id: 'cipher-bearcamp',
    title: 'The Bearcamp River Paddleford Sentinel',
    town: 'West Ossipee, NH',
    riddle: 'I span the cold Bearcamp where poet Whittier wrote in rhyme. Wooden trusses shelter travelers against the frost of time. Search the eastern portal timber for the beacon in the pine.',
    encodedClue: 'OLD-RTE-125 // WHITTIER-TIMBER-TRUSS // 43.7912° N, 71.1890° W',
    locationHint: 'Whittier Covered Bridge (1870 Heritage Marker)',
    solutionPasscode: 'BEARCAMP1870',
    associatedBeaconTagId: 'NFC-HUNT-OSS-03',
    xpReward: 150,
    bountyRewardText: '15% Off Yankee Smokehouse BBQ Platter',
    isSolved: false,
  },
  {
    id: 'cipher-whistling-pine',
    title: 'The Glacial Shore Observation Watch',
    town: 'Center Ossipee, NH',
    riddle: 'Carved by ice twelve thousand winters past, I gaze toward Chocorua tall and vast. Look beneath the wooden pavilion where public boats cast off at last.',
    encodedClue: 'ROUTE-25 // PINE-POINT-SHORELINE // 43.7420° N, 71.1340° W',
    locationHint: 'Ossipee Lake Natural Public Shore Pavilion',
    solutionPasscode: 'OSSIPEESHORE',
    associatedBeaconTagId: 'NFC-HUNT-OSS-01',
    xpReward: 150,
    bountyRewardText: 'Free Iced Beverage with Canoe Rental',
    isSolved: false,
  },
  {
    id: 'cipher-effingham-hearth',
    title: 'The Historic Route 25 Hearth Beacon',
    town: 'Effingham, NH',
    riddle: 'Where steak and cheese sizzles on the roadside iron grill, and sourdough boules rise warm against the autumn chill. Tap the beacon at the counter to claim your hearty fill.',
    encodedClue: 'NH-25 // PNB-ROADSIDE-GRILL // 43.7540° N, 71.0110° W',
    locationHint: 'PNB Eats Roadside Grill Welcome Counter',
    solutionPasscode: 'EFFINGHAMHEARTH',
    associatedBeaconTagId: 'NFC-HUNT-EFF-01',
    xpReward: 150,
    bountyRewardText: '$5 Off Any Hot Sub & Fried Dough Bites',
    isSolved: false,
  },
  {
    id: 'cipher-freedom-stage',
    title: 'The Green Stage Folk & Blues Relic',
    town: 'Freedom, NH',
    riddle: 'Where acoustics echo off white church spires and mountain air, fiddle strings vibrate through the summer village square. Find the acoustic medallion near the gazebo stair.',
    encodedClue: 'FREEDOM-VILLAGE-GREEN // 43.8115° N, 71.0370° W',
    locationHint: 'Freedom Town Green Historic Gazebo',
    solutionPasscode: 'FREEDOMFOLK',
    associatedBeaconTagId: 'NFC-HUNT-FRD-01',
    xpReward: 200,
    bountyRewardText: 'VIP Festival Pass Upgrade Token',
    isSolved: false,
  }
];

export const PRESET_SOCIETY_MEMBERS: SocietyMemberProfile[] = [
  {
    id: 'soc-sean',
    alias: 'Sean Martin',
    chapter: 'Effingham Vanguard Chapter',
    rank: 'Grand Sovereign',
    rankLevel: 5,
    xp: 1480,
    totalCheckpointsClaimed: 34,
    bountiesEarnedTotal: 12,
    badges: ['👑 Sovereign Master', '🌲 White Mountain Pioneer', '⚡ Hardware Architect', '🗝️ Master Cryptographer', '🚚 Vanguard Courier Lead'],
    joinedDate: '2026-01-01',
    avatarEmoji: '👑',
    nfcPassId: 'PASS-SOVEREIGN-001',
  },
  {
    id: 'soc-walt',
    alias: 'Walt Henderson',
    chapter: 'Effingham Artisan Guild',
    rank: 'Town Vanguard',
    rankLevel: 3,
    xp: 710,
    totalCheckpointsClaimed: 21,
    bountiesEarnedTotal: 6,
    badges: ['🪵 Master Woodcrafter', '🌲 Trail Tracker', '⭐ 5-Star Patron'],
    joinedDate: '2026-02-15',
    avatarEmoji: '🔨',
    nfcPassId: 'PASS-VANGUARD-042',
  },
  {
    id: 'soc-gary',
    alias: 'Gary Collins',
    chapter: 'Route 25 Merchant Union',
    rank: 'Town Vanguard',
    rankLevel: 3,
    xp: 680,
    totalCheckpointsClaimed: 18,
    bountiesEarnedTotal: 5,
    badges: ['🥪 Hearth Kitchenmaster', '⚡ Beacon Host', '🤝 Community Anchor'],
    joinedDate: '2026-03-01',
    avatarEmoji: '🥪',
    nfcPassId: 'PASS-VANGUARD-088',
  },
  {
    id: 'soc-sarah',
    alias: 'Sarah Jenkins',
    chapter: 'Carroll County Forage & Flora',
    rank: 'Trail Pioneer',
    rankLevel: 2,
    xp: 420,
    totalCheckpointsClaimed: 12,
    bountiesEarnedTotal: 4,
    badges: ['🐝 Chaga & Honey Master', '🗺️ Trail Explorer'],
    joinedDate: '2026-04-10',
    avatarEmoji: '🍯',
    nfcPassId: 'PASS-PIONEER-112',
  },
  {
    id: 'soc-alex',
    alias: 'Alex Tremblay',
    chapter: 'Freedom Lakehouse Circle',
    rank: 'Trail Pioneer',
    rankLevel: 2,
    xp: 380,
    totalCheckpointsClaimed: 9,
    bountiesEarnedTotal: 3,
    badges: ['🏡 Superhost Concierge', '🌊 Lake Seeker'],
    joinedDate: '2026-05-01',
    avatarEmoji: '🌲',
    nfcPassId: 'PASS-PIONEER-204',
  }
];
