import { StoreHuntCircuit, StoreHunterStamp } from './types';

export const INITIAL_STORE_CIRCUITS: StoreHuntCircuit[] = [
  {
    id: 'circuit-antiques-thrift',
    title: 'Carroll County Antique, Vintage & Thrift Trail',
    slug: 'carroll-county-antique-trail',
    category: 'antiques',
    categoryLabel: 'Antiques & Vintage Barns',
    region: 'Carroll County, NH',
    townsCovered: ['Ossipee', 'Effingham', 'Wolfeboro', 'Freedom'],
    badgeName: 'Master Antique Hunter',
    badgeIcon: '🏺',
    description: 'Hunt through multi-dealer antique barns, salvaged architectural relics, estate jewelry, retro vinyl, and classic New England farmhouse collectibles.',
    theme: 'Vintage Treasures & Barn Pickers',
    coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 175,
    circuitBonusReward: '$10.00 Regional Antique & Thrift Voucher',
    circuitBonusCode: 'ANTIQUE-HUNTER-10',
    circuitBonusDiscount: '$10 OFF',
    activeHuntersCount: 184,
    completedHuntersCount: 121,
    spots: [
      {
        id: 'spot-antique-1',
        storeName: 'Bearcamp River Vintage & Antiques',
        town: 'Ossipee',
        category: 'antiques',
        categoryLabel: 'Antique Barn',
        address: 'Route 25 & Bearcamp Rd, West Ossipee, NH',
        phone: '(603) 539-7700',
        hours: 'Wed - Sun: 10:00 AM - 5:00 PM',
        tagline: 'Two-story restored timber barn featuring 30+ independent antique dealers.',
        description: 'Specializes in early American primitive pine furniture, cast iron skillets, stained glass windows, and vintage Carroll County road signs.',
        coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-BEARCAMP-01',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-antiques-thrift&spot=spot-antique-1',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '45 mins (Sean Martin 4x4)',
        ownerName: 'Eleanor & Frank Vance',
        mysteryPerk: {
          discountLabel: '15% Off Any Glassware or Primitive Collectible',
          discountDescription: 'Flash at checkout register or tap with mobile wallet to apply instant 15% discount.',
          voucherCode: 'BEARCAMP-15-GLASS',
          minimumSpend: '$20 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-antique-2',
        storeName: "Lord's Hill Heritage Salvage & Books",
        town: 'Effingham',
        category: 'antiques',
        categoryLabel: 'Rare Books & Architectural Salvage',
        address: 'Plantation Rd & Historic Square, Effingham, NH',
        phone: '(603) 539-8420',
        hours: 'Thu - Sun: 11:00 AM - 4:30 PM',
        tagline: '1800s first-edition volumes, antique maps, brass hardware, and hand-hewn mantels.',
        description: 'Nestled in historic Lord’s Hill, this quaint emporium curates century-old literature, botanical prints, and reclaimed carriage house artifacts.',
        coverImage: 'https://images.unsplash.com/photo-1507842229450-7907945d8b88?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-LORDSHILL-02',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-antiques-thrift&spot=spot-antique-2',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '30 mins',
        ownerName: 'Abigail Sterling',
        mysteryPerk: {
          discountLabel: 'Free 1920s Historic Postcard + 10% Off Rare Books',
          discountDescription: 'Choose any authentic archival postcard from the wooden display rack with any book purchase.',
          voucherCode: 'LORDSHILL-POSTCARD-FREE',
          minimumSpend: 'No minimum',
          expiresInDays: 45
        }
      },
      {
        id: 'spot-antique-3',
        storeName: 'Wolfeboro Nautical & Vintage Co.',
        town: 'Wolfeboro',
        category: 'antiques',
        categoryLabel: 'Lakeside Vintage Decor',
        address: '42 Main St, Wolfeboro, NH',
        phone: '(603) 569-3112',
        hours: 'Daily: 9:30 AM - 6:00 PM',
        tagline: 'Vintage mahogany boat steering wheels, brass ship lanterns, and Lake Winnipesaukee memorabilia.',
        description: 'Premier downtown destination for authentic nautical antiques, mid-century lakeside lodge furniture, and collectible brass clocks.',
        coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-WOLFNAUT-03',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-antiques-thrift&spot=spot-antique-3',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '60 mins',
        ownerName: 'Captain Dave Miller',
        mysteryPerk: {
          discountLabel: '$5.00 Off Any Maritime or Lodge Artifact',
          discountDescription: 'Instant $5 register credit applied to any nautical decor item or brass lantern.',
          voucherCode: 'WOLFE-NAUTICAL-5',
          minimumSpend: '$25 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-antique-4',
        storeName: 'Freedom Village Barn Treasures',
        town: 'Freedom',
        category: 'antiques',
        categoryLabel: 'Hand-Restored Rustic Decor',
        address: 'Old Mill Brook Rd, Freedom, NH',
        phone: '(603) 539-2240',
        hours: 'Fri - Sun: 10:00 AM - 5:00 PM',
        tagline: 'Restored farmhouse tables, milk paint cupboards, and hand-woven New England textiles.',
        description: 'A cozy country barn overflowing with hand-sanded farm tables, antique enamelware, vintage quilts, and wrought iron garden trellises.',
        coverImage: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-FREEDOMBARN-04',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-antiques-thrift&spot=spot-antique-4',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '40 mins',
        ownerName: 'Sarah & Ben Thorne',
        mysteryPerk: {
          discountLabel: '10% Off Hand-Restored Furniture or Home Textile',
          discountDescription: 'Enjoy 10% off any barn piece or handmade country textile runner.',
          voucherCode: 'FREEDOM-RUSTIC-10',
          minimumSpend: '$30 minimum purchase',
          expiresInDays: 30
        }
      }
    ]
  },
  {
    id: 'circuit-farmstands-bakeries',
    title: 'Farmstands, Bakeries & Sugar Shacks Hunt',
    slug: 'farmstands-bakeries-sugar-shacks',
    category: 'farmstands',
    categoryLabel: 'Farmstands & Artisan Bakeries',
    region: 'Carroll County, NH',
    townsCovered: ['Effingham', 'Ossipee', 'Freedom', 'Tamworth'],
    badgeName: 'Local Harvest Connoisseur',
    badgeIcon: '🥖',
    description: 'Hunt for wood-fired maple sugar shacks, wild blueberry pies, sourdough boules, raw honeycombs, and small-batch goat cheeses.',
    theme: 'Fresh Baked Sourdough, Maple & Farmstands',
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 175,
    circuitBonusReward: '$10.00 Farmstand & Fresh Harvest Shopping Voucher',
    circuitBonusCode: 'HARVEST-HUNTER-10',
    circuitBonusDiscount: '$10 OFF',
    activeHuntersCount: 240,
    completedHuntersCount: 178,
    spots: [
      {
        id: 'spot-farm-1',
        storeName: 'Effingham Valley Sugarhouse & Honey Apiary',
        town: 'Effingham',
        category: 'farmstand',
        categoryLabel: 'Maple & Honey Stand',
        address: 'Province Lake Rd, Effingham, NH',
        phone: '(603) 539-1104',
        hours: 'Daily: 8:00 AM - 6:00 PM (Honor Box & Counter)',
        tagline: 'Pure Grade-A Amber Rich Maple Syrup & Raw Wildflower Honey.',
        description: 'Tapping 1,200 mountain maples with wood-fired evaporator. Also offering maple candy leaves, maple bourbon syrup, and pure beeswax candles.',
        coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-EFFMAPLE-01',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-farmstands-bakeries&spot=spot-farm-1',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '25 mins (Sean Martin 4x4)',
        ownerName: 'Dan & Martha Hobbs',
        mysteryPerk: {
          discountLabel: 'Free 2oz Pure Amber Maple Syrup Bottle',
          discountDescription: 'Receive a complimentary glass gift bottle of pure wood-fired maple syrup with any in-store purchase.',
          voucherCode: 'EFFINGHAM-FREE-MAPLE2OZ',
          minimumSpend: '$10 minimum purchase',
          expiresInDays: 60
        }
      },
      {
        id: 'spot-farm-2',
        storeName: 'Pine Cone Artisan Sourdough Bakehouse',
        town: 'Ossipee',
        category: 'bakery',
        categoryLabel: 'Stone-Oven Bakehouse',
        address: 'Route 16 & Granite Rd, Center Ossipee, NH',
        phone: '(603) 539-9300',
        hours: 'Wed - Sun: 7:00 AM - 2:00 PM (Until Sold Out)',
        tagline: 'Naturally fermented artisan sourdough loaves, cardamom buns, and breakfast hand-pies.',
        description: 'Baked fresh daily at 5 AM using certified organic NH stone-ground flour and 48-hour cold fermentation techniques.',
        coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-PINECONE-02',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-farmstands-bakeries&spot=spot-farm-2',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '20 mins',
        ownerName: 'Clara Johansson',
        mysteryPerk: {
          discountLabel: 'Free Warm Sourdough Pretzel or Cinnamon Twist',
          discountDescription: 'Claim one fresh-baked sourdough pretzel with coarse sea salt when ordering any coffee or artisan loaf.',
          voucherCode: 'PINECONE-FREE-PRETZEL',
          minimumSpend: '$5 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-farm-3',
        storeName: 'Freedom Brook Farm & Creamery',
        town: 'Freedom',
        category: 'farmstand',
        categoryLabel: 'Artisan Cheeses & Pasture Eggs',
        address: 'Village Green Brook Rd, Freedom, NH',
        phone: '(603) 539-4480',
        hours: 'Tue - Sun: 9:00 AM - 5:00 PM',
        tagline: 'Small-batch cave-aged cheddar, goat chèvre, pasture-raised eggs, and heritage pork.',
        description: 'Pasture-centered family farm producing award-winning cheeses aged right here in cold stone cellars with zero artificial preservatives.',
        coverImage: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-FREEDOMCHEESE-03',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-farmstands-bakeries&spot=spot-farm-3',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '35 mins',
        ownerName: 'Timothy & Lisa Walsh',
        mysteryPerk: {
          discountLabel: '10% Off Any Farmstead Cheese Wheel or Chèvre Tub',
          discountDescription: 'Enjoy 10% off any hand-crafted farm cheese or organic fresh yogurt jar.',
          voucherCode: 'FREEDOM-CHEESE-10',
          minimumSpend: '$15 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-farm-4',
        storeName: 'Tamworth Lyceum Organic Provisions & Pantry',
        town: 'Tamworth',
        category: 'farmstand',
        categoryLabel: 'Curated Farm Provisions',
        address: '85 Main St, Tamworth, NH',
        phone: '(603) 323-8600',
        hours: 'Daily: 8:00 AM - 5:00 PM',
        tagline: 'Specialty coffee bar, locally roasted nuts, heirloom jams, and organic provisions.',
        description: 'The historic village center meeting house stocked with local pantry goods, handcrafted pottery, organic baking mixes, and fresh herbal infusions.',
        coverImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-TAMLYCEUM-04',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-farmstands-bakeries&spot=spot-farm-4',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '30 mins',
        ownerName: 'Garrison & Emily Frost',
        mysteryPerk: {
          discountLabel: 'Buy 1 Specialty Coffee, Get 1 Fresh Scone / Muffin Free',
          discountDescription: 'Pair your morning espresso or pour-over with a complimentary artisan bakery pastry.',
          voucherCode: 'LYCEUM-BOGO-PASTRY',
          minimumSpend: '$4 minimum purchase',
          expiresInDays: 30
        }
      }
    ]
  },
  {
    id: 'circuit-woodcraft-outfitters',
    title: 'Woodcraft, Blacksmith & North Country Outfitters Trail',
    slug: 'woodcraft-blacksmith-outfitters',
    category: 'trades_outfitters',
    categoryLabel: 'Trades, Woodcraft & Gear',
    region: 'Carroll County, NH',
    townsCovered: ['Effingham', 'Conway', 'Tamworth', 'Ossipee'],
    badgeName: 'North Country Pioneer',
    badgeIcon: '🪵',
    description: 'Hunt for master timber framers, custom live-edge tables, hand-forged wrought iron fire pokers, and rugged mountain expedition gear.',
    theme: 'Timber Carpentry, Ironwork & Mountain Gear',
    coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 175,
    circuitBonusReward: '$15.00 Custom Trades & Outfitter Voucher',
    circuitBonusCode: 'TRADES-PIONEER-15',
    circuitBonusDiscount: '$15 OFF',
    activeHuntersCount: 165,
    completedHuntersCount: 95,
    spots: [
      {
        id: 'spot-wood-1',
        storeName: "Walt's Handcrafted Timber & Furniture Showroom",
        town: 'Effingham',
        category: 'crafts',
        categoryLabel: 'Master Woodcraft Workshop',
        address: '14 Elm St, Effingham, NH',
        phone: '(603) 539-8120',
        hours: 'Mon - Sat: 8:00 AM - 5:00 PM',
        tagline: 'Custom live-edge dining tables, butcher blocks, and hand-turned maple bowls.',
        description: 'Master carpenter Walter Henderson crafts heirloom furniture from locally sourced fallen white pine, red oak, and black walnut.',
        coverImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-WALTS-01',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-woodcraft-outfitters&spot=spot-wood-1',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '45 mins (Subaru AWD Vanguard)',
        ownerName: 'Walter Henderson',
        mysteryPerk: {
          discountLabel: 'Free Organic Beeswax Board Conditioning Tin ($12 Value)',
          discountDescription: 'Keep your cutting boards and timber furniture protected with pure local beeswax salve.',
          voucherCode: 'WALTS-FREE-WAX',
          minimumSpend: '$25 minimum purchase',
          expiresInDays: 45
        }
      },
      {
        id: 'spot-wood-2',
        storeName: 'Mount Washington Trail & Mountain Outfitter',
        town: 'Conway',
        category: 'outfitter',
        categoryLabel: 'Expedition & 4x4 Gear',
        address: '56 Main St, North Conway, NH',
        phone: '(603) 356-5500',
        hours: 'Daily: 8:30 AM - 7:00 PM',
        tagline: 'All-weather mountain apparel, wool blankets, snowshoes, and 4x4 vehicle recovery gear.',
        description: 'Equipping hikers, climbers, and mountain couriers for the rugged White Mountain terrain with field-tested gear and trail maps.',
        coverImage: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-CONWAYGEAR-02',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-woodcraft-outfitters&spot=spot-wood-2',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '30 mins',
        ownerName: 'Jackson Reid',
        mysteryPerk: {
          discountLabel: '15% Off Merino Wool Socks, Camp Flasks & Trail Lanterns',
          discountDescription: 'Tap in-store to unlock instant 15% discount on all outdoor accessories.',
          voucherCode: 'CONWAY-TRAIL-15',
          minimumSpend: '$20 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-wood-3',
        storeName: 'Chocorua Forge & Blacksmith Studio',
        town: 'Tamworth',
        category: 'crafts',
        categoryLabel: 'Hand-Forged Ironworks',
        address: '120 Mountain View Rd, Tamworth, NH',
        phone: '(603) 323-7110',
        hours: 'Wed - Sun: 10:00 AM - 4:00 PM',
        tagline: 'Hand-hammered coal-forge fireplace pokers, barn door handles, and kitchen hooks.',
        description: 'Traditional coal-fired blacksmith forge transforming raw steel and copper into functional New England home hardware and architectural accents.',
        coverImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-CHOCORUA-03',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-woodcraft-outfitters&spot=spot-wood-3',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '40 mins',
        ownerName: 'Ethan Cole',
        mysteryPerk: {
          discountLabel: 'Free Hand-Forged S-Hook Gift with Any $25 Order',
          discountDescription: 'Receive an authentic hand-twisted blacksmith S-hook for hanging cast iron pans or plants.',
          voucherCode: 'CHOCORUA-FREE-SHOOK',
          minimumSpend: '$25 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-wood-4',
        storeName: 'Carroll County 4x4 Hardware & Power Hub',
        town: 'Ossipee',
        category: 'outfitter',
        categoryLabel: 'Tools & Vehicle Recovery',
        address: 'Route 16 Commercial Strip, Ossipee, NH',
        phone: '(603) 539-4400',
        hours: 'Mon - Sat: 7:00 AM - 6:00 PM',
        tagline: 'Chainsaw bars, snow chains, winch cables, and heavy rural workwear.',
        description: 'Supplying Carroll County trade contractors, timber loggers, and emergency snow recovery drivers with heavy-duty gear.',
        coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-4X4OSS-04',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-woodcraft-outfitters&spot=spot-wood-4',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '15 mins (Sean Martin Dispatch)',
        ownerName: 'Sean Martin & Rick Hall',
        mysteryPerk: {
          discountLabel: 'Free Chainsaw / Axe Blade Sharpening Token',
          discountDescription: 'Bring any chainsaw chain or camping axe for precision shop sharpening free of charge.',
          voucherCode: '4X4-SHARPEN-FREE',
          minimumSpend: '$10 in-store purchase',
          expiresInDays: 60
        }
      }
    ]
  },
  {
    id: 'circuit-sweets-coffee',
    title: 'Lakeside Coffee, Chocolatiers & Sweet Treat Crawl',
    slug: 'coffee-chocolate-sweet-treats',
    category: 'sweets_coffee',
    categoryLabel: 'Coffee, Fudge & Ice Cream',
    region: 'Carroll County, NH',
    townsCovered: ['Wolfeboro', 'Ossipee', 'Tamworth'],
    badgeName: 'Sweet Tooth Explorer',
    badgeIcon: '☕',
    description: 'Hunt for copper-kettle handmade fudge, micro-batch espresso roasters, lakeside waffle cones, and artisan truffles.',
    theme: 'Handmade Fudge, Artisan Roasters & Ice Cream',
    coverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 140,
    circuitBonusReward: '$5.00 Sweet Treat & Coffee Flight Voucher',
    circuitBonusCode: 'SWEETS-EXPLORER-5',
    circuitBonusDiscount: '$5.00 OFF',
    activeHuntersCount: 290,
    completedHuntersCount: 215,
    spots: [
      {
        id: 'spot-sweet-1',
        storeName: 'Wolfeboro Bay Chocolate & Fudge Works',
        town: 'Wolfeboro',
        category: 'cafe',
        categoryLabel: 'Handmade Chocolate Factory',
        address: '18 N Main St, Wolfeboro, NH',
        phone: '(603) 569-8080',
        hours: 'Daily: 10:00 AM - 8:00 PM',
        tagline: 'Fresh copper-kettle fudge slabs, sea salt caramels, and dark chocolate barks.',
        description: 'Watch candy makers pour hot boiling maple fudge onto heavy marble cooling tables right through the viewing window.',
        coverImage: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-WOLFFUDGE-01',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-sweets-coffee&spot=spot-sweet-1',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '45 mins',
        ownerName: 'Brenda & Liam O’Connor',
        mysteryPerk: {
          discountLabel: 'Free Hand-Dipped Chocolate Truffle of Choice',
          discountDescription: 'Select any gourmet truffle from the display glass when purchasing a 1/2 lb of fudge.',
          voucherCode: 'WOLFE-FREE-TRUFFLE',
          minimumSpend: '$12 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-sweet-2',
        storeName: 'Ossipee Lake Creamery & Waffle Hut',
        town: 'Ossipee',
        category: 'cafe',
        categoryLabel: 'Lakeside Ice Cream Stand',
        address: 'Route 25 Marina Turnoff, Center Ossipee, NH',
        phone: '(603) 539-6500',
        hours: 'Daily: 11:30 AM - 9:00 PM',
        tagline: 'Homemade high-butterfat ice cream with hand-rolled warm waffle cones.',
        description: 'Featuring 24 rotating flavors including Wild NH Blueberry, Maple Walnut Swirl, and Dark Chocolate Mud Pie.',
        coverImage: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-OSSICREAM-02',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-sweets-coffee&spot=spot-sweet-2',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '20 mins',
        ownerName: 'Marcus Bennett',
        mysteryPerk: {
          discountLabel: 'Free Hand-Rolled Waffle Cone Upgrade',
          discountDescription: 'Enjoy a free freshly made warm waffle cone with any double-scoop ice cream cup.',
          voucherCode: 'OSSI-FREE-CONE',
          minimumSpend: '$6 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-sweet-3',
        storeName: 'Tamworth Village Tea & Botanical Emporium',
        town: 'Tamworth',
        category: 'cafe',
        categoryLabel: 'Organic Herbal Teas & Apothecary',
        address: '22 Main St, Tamworth, NH',
        phone: '(603) 323-9090',
        hours: 'Tue - Sun: 9:00 AM - 4:30 PM',
        tagline: 'Hand-blended loose leaf mountain teas, elderberry elixirs, and local wildflower tisanes.',
        description: 'Sourcing wild-harvested herbs, chaga mushrooms, and dried florals from the White Mountain foothills for invigorating wellness brews.',
        coverImage: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-TAMTEA-03',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-sweets-coffee&spot=spot-sweet-3',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '30 mins',
        ownerName: 'Maya Greenwood',
        mysteryPerk: {
          discountLabel: 'Free Mountain Herb Tea Sample Tin ($8 Value)',
          discountDescription: 'Receive a pocket sample tin of loose-leaf White Mountain Forest Blend tea with any order.',
          voucherCode: 'TAMWORTH-FREE-TEA',
          minimumSpend: '$15 minimum purchase',
          expiresInDays: 45
        }
      },
      {
        id: 'spot-sweet-4',
        storeName: 'Lone Wolfe Micro-Roastery & Espresso Bar',
        town: 'Wolfeboro',
        category: 'cafe',
        categoryLabel: 'Specialty Coffee Roaster',
        address: '36 Mill St, Wolfeboro, NH',
        phone: '(603) 569-4040',
        hours: 'Daily: 6:30 AM - 3:00 PM',
        tagline: 'Direct-trade beans roasted in small batches on vintage cast iron drum roasters.',
        description: 'Single-origin pour overs, velvety nitro cold brews, and house-made vanilla bean syrups crafted daily.',
        coverImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-LONEWOLFE-04',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-sweets-coffee&spot=spot-sweet-4',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '35 mins',
        ownerName: 'Graham Shaw',
        mysteryPerk: {
          discountLabel: 'Free 4oz Sample Bag of Whole Bean Mountain Roast',
          discountDescription: 'Take home a freshly roasted coffee sample bag with any bagged whole bean purchase.',
          voucherCode: 'WOLFE-FREE-BEANS4OZ',
          minimumSpend: '$15 minimum purchase',
          expiresInDays: 30
        }
      }
    ]
  },
  {
    id: 'circuit-country-mercantiles',
    title: 'Historic Country General Stores & Mercantiles',
    slug: 'historic-country-general-stores',
    category: 'mercantile',
    categoryLabel: 'General Stores & Mercantiles',
    region: 'Carroll County, NH',
    townsCovered: ['Ossipee', 'Freedom', 'Tamworth', 'Conway'],
    badgeName: 'Heritage Mercantile Scout',
    badgeIcon: '🏬',
    description: 'Hunt for vintage creaky wooden floorboards, glass jars of penny candy, local smoked meats, wool socks, and community news hubs.',
    theme: 'Historic General Stores & Penny Candy Counters',
    coverImage: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 140,
    circuitBonusReward: '$10.00 Historic Mercantile Credit',
    circuitBonusCode: 'MERCANTILE-HERITAGE-10',
    circuitBonusDiscount: '$10 OFF',
    activeHuntersCount: 210,
    completedHuntersCount: 155,
    spots: [
      {
        id: 'spot-merc-1',
        storeName: 'Center Ossipee Country Store & Deli Counter',
        town: 'Ossipee',
        category: 'mercantile',
        categoryLabel: 'Historic Country Store',
        address: 'Main St & Depot Rd, Center Ossipee, NH',
        phone: '(603) 539-4321',
        hours: 'Daily: 6:00 AM - 7:00 PM',
        tagline: 'Serving Carroll County since 1888 with fresh deli grinders and penny candy.',
        description: 'The authentic heart of Center Ossipee featuring hot breakfast sandwiches, aged wheel cheddar cut to order, and hunting supplies.',
        coverImage: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-OSSSTORE-01',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-country-mercantiles&spot=spot-merc-1',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '15 mins',
        ownerName: 'Frank & Betty Ross',
        mysteryPerk: {
          discountLabel: 'Free Old-Fashioned Penny Candy Bag ($5 Value)',
          discountDescription: 'Fill an authentic brown paper bag with vintage candy sticks and salt water taffy.',
          voucherCode: 'OSSI-FREE-CANDY',
          minimumSpend: '$10 deli order',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-merc-2',
        storeName: 'Freedom Village General Store',
        town: 'Freedom',
        category: 'mercantile',
        categoryLabel: 'Village General Store',
        address: 'Village Green, Freedom, NH',
        phone: '(603) 539-7100',
        hours: 'Mon - Sat: 7:00 AM - 6:00 PM, Sun: 8:00 AM - 4:00 PM',
        tagline: 'Preserving small-town heritage with local dairy, fresh pies, and craft provisions.',
        description: 'Centrally located on the Freedom Village Green across from the church, offering home-cooked daily soups, local honey, and gift wares.',
        coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-FREEDOMSTORE-02',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-country-mercantiles&spot=spot-merc-2',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '25 mins',
        ownerName: 'Nancy Harmon',
        mysteryPerk: {
          discountLabel: '10% Off Local Smoked Meats, Sausages & Cheeses',
          discountDescription: 'Save 10% on your purchase of artisan butcher cuts and farm provisions.',
          voucherCode: 'FREEDOM-MEAT-10',
          minimumSpend: '$15 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-merc-3',
        storeName: 'Tamworth Village Mercantile & Hardware',
        town: 'Tamworth',
        category: 'mercantile',
        categoryLabel: 'General Mercantile',
        address: '40 Main St, Tamworth, NH',
        phone: '(603) 323-5520',
        hours: 'Mon - Sat: 7:30 AM - 5:30 PM',
        tagline: 'New England ironmongery, cast iron cookware, and local artisan gifts.',
        description: 'A genuine village fixture stocking everything from galvanized buckets and seed packets to handmade soaps and maple sugar.',
        coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-TAMMERC-03',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-country-mercantiles&spot=spot-merc-3',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '30 mins',
        ownerName: 'Arthur Pendelton',
        mysteryPerk: {
          discountLabel: '$5.00 Off Any Local Craft Pottery or Handmade Soap Set',
          discountDescription: 'Instant $5 discount applied to any artisan gift shelf item.',
          voucherCode: 'TAMWORTH-CRAFT-5',
          minimumSpend: '$20 minimum purchase',
          expiresInDays: 30
        }
      },
      {
        id: 'spot-merc-4',
        storeName: 'Conway Depot General Provisions & Outpost',
        town: 'Conway',
        category: 'mercantile',
        categoryLabel: 'Depot Mercantile',
        address: '12 Railroad Plaza, Conway, NH',
        phone: '(603) 447-3300',
        hours: 'Daily: 8:00 AM - 6:30 PM',
        tagline: 'Railroad junction general goods, homemade jams, and North Country snacks.',
        description: 'Located by the historic tracks, supplying travelers with fresh hot coffee, local berry preserves, trail snacks, and regional souvenirs.',
        coverImage: 'https://images.unsplash.com/photo-1507842229450-7907945d8b88?auto=format&fit=crop&w=600&q=80',
        nfcTagId: 'NFC-STORE-CONWAYDEPOT-04',
        qrPayloadUrl: 'https://oasistap.local/store-hunting?circuit=circuit-country-mercantiles&spot=spot-merc-4',
        pointsReward: 35,
        isCourierAvailable: true,
        courierLeadTime: '35 mins',
        ownerName: 'Henry Kowalski',
        mysteryPerk: {
          discountLabel: '15% Off North Country Wild Blackberry & Maple Jams',
          discountDescription: 'Enjoy 15% off any jar of locally jarred fruit preserves and mountain spreads.',
          voucherCode: 'CONWAY-JAM-15',
          minimumSpend: '$10 minimum purchase',
          expiresInDays: 30
        }
      }
    ]
  }
];

export const INITIAL_STORE_HUNTER_STAMPS: StoreHunterStamp[] = [
  {
    spotId: 'spot-antique-1',
    storeName: 'Bearcamp River Vintage & Antiques',
    circuitId: 'circuit-antiques-thrift',
    town: 'Ossipee',
    timestamp: '2026-09-21T15:20:00Z',
    badgeIcon: '🏺',
    pointsEarned: 35,
    verifiedVia: 'nfc',
    unlockedPerk: {
      discountLabel: '15% Off Any Glassware or Primitive Collectible',
      discountDescription: 'Flash at checkout register or tap with mobile wallet to apply instant 15% discount.',
      voucherCode: 'BEARCAMP-15-GLASS',
      minimumSpend: '$20 minimum purchase',
      expiresInDays: 30
    }
  }
];
