import { TouristHunt, PassportStamp } from './types';

export const INITIAL_TOURIST_HUNTS: TouristHunt[] = [
  {
    id: 'hunt-ossipee-pioneer',
    title: 'Ossipee Lake & Mountain Pioneer Trail',
    slug: 'ossipee-mountain-pioneer',
    town: 'Ossipee',
    region: 'Carroll County, NH',
    badgeName: 'Ossipee Mountain Pioneer',
    badgeIcon: '🌲',
    difficulty: 'Easy',
    estimatedDuration: '1.5 - 2 Hours',
    description: 'Explore the historic railroad roots, iconic 1870 covered timber bridges, panoramic lake beaches, and scenic mountain views of Ossipee.',
    theme: 'Railroad History & Scenic Waters',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 250,
    bonusVoucherTitle: '15% Off Yankee Smokehouse BBQ & Farm Stand',
    bonusVoucherCode: 'OSSIPEE-PIONEER-15',
    bonusVoucherDiscount: '15% OFF',
    participatingCount: 142,
    completedCount: 98,
    checkpoints: [
      {
        id: 'cp-ossipee-1',
        name: 'Ossipee Lake Natural Public Shore',
        town: 'Ossipee',
        category: 'scenic',
        description: 'Vast scenic vista over Ossipee Lake with backdrop views of the Ossipee Mountain Range and Mount Chocorua.',
        historicalNote: 'Glacial lake formed over 12,000 years ago, serving as a historic summer meeting hub for indigenous Abenaki and early 1700s settlers.',
        clue: 'Find the wooden observation pavilion overlooking the eastern pine point by the public boat launch.',
        address: 'Route 25 & Ossipee Lake Rd, Center Ossipee, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-OSS-01',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-ossipee-pioneer&checkin=cp-ossipee-1',
        photoUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Ossipee Lake Marina',
        sponsorOffer: 'Free iced tea with canoe rental'
      },
      {
        id: 'cp-ossipee-2',
        name: 'Historic Boston & Maine Railroad Station Depot',
        town: 'Ossipee',
        category: 'historic',
        description: 'Authentic 1870s wooden depot and telegraph station that once connected Carroll County lumber mills to Boston.',
        historicalNote: 'The Northern Railroad brought thousands of summer tourists and granite quarry workers here in the late 19th century.',
        clue: 'Look for the restored cast-iron train signal bell on the heritage platform.',
        address: 'Main St & Railroad Ave, Center Ossipee, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-OSS-02',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-ossipee-pioneer&checkin=cp-ossipee-2',
        photoUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-ossipee-3',
        name: 'Whittier Covered Bridge Heritage Marker',
        town: 'Ossipee',
        category: 'bridge',
        description: 'Historic 1870 timber paddleford truss covered bridge spanning the Bearcamp River, dedicated to poet John Greenleaf Whittier.',
        historicalNote: 'One of New Hampshire’s most cherished surviving covered bridges, renovated to preserve 19th-century woodworking craftsmanship.',
        clue: 'Search near the eastern portal entrance sign for the wooden NFC medallion.',
        address: 'Old Route 125 over Bearcamp River, West Ossipee, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-OSS-03',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-ossipee-pioneer&checkin=cp-ossipee-3',
        photoUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-ossipee-4',
        name: 'Carroll County Pioneer Ridge Overlook',
        town: 'Ossipee',
        category: 'nature',
        description: 'High vantage point offering 180-degree sightlines across Carroll County forest canopy and Mount Shaw.',
        historicalNote: 'Early settlers and fire watchmen used this high stone outcropping to signal between Ossipee and Effingham valleys.',
        clue: 'Located at the scenic picnic pull-off marker with the granite stone bench.',
        address: 'Route 16 Scenic Pull-Off, Ossipee, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-OSS-04',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-ossipee-pioneer&checkin=cp-ossipee-4',
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-ossipee-5',
        name: 'Yankee Smokehouse Regional Tap Hub',
        town: 'Ossipee',
        category: 'food_drink',
        description: 'World-famous roadside smoked BBQ joint, motorcycle stop, and Carroll County community bulletin station.',
        historicalNote: 'A staple meeting junction for over 40 years where north-south travelers pause for hickory-smoked meats and local news.',
        clue: 'Tap the Townraise NFC badge right at the front welcome counter next to the menu blackboard.',
        address: 'Junction Route 16 & Route 25, West Ossipee, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-OSS-05',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-ossipee-pioneer&checkin=cp-ossipee-5',
        photoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Yankee Smokehouse',
        sponsorOffer: 'Free side of cornbread with any BBQ platter'
      }
    ]
  },
  {
    id: 'hunt-effingham-freedom-artisan',
    title: 'Effingham & Freedom Heritage Mill & Artisan Trail',
    slug: 'effingham-freedom-artisan-trail',
    town: 'Effingham & Freedom',
    region: 'Carroll County, NH',
    badgeName: 'Valley Artisan Explorer',
    badgeIcon: '🍁',
    difficulty: 'Easy',
    estimatedDuration: '1 - 1.5 Hours',
    description: 'Discover the tranquil 1800s architecture of Lord’s Hill, babbling mill brooks, footbridges, and artisan maple sugar shacks.',
    theme: 'Historic Meetinghouses, Bridges & Country Sugaring',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 200,
    bonusVoucherTitle: 'Free Artisan Maple / Honey Tasting + 10% Off Local Crafts',
    bonusVoucherCode: 'VALLEY-ARTISAN-10',
    bonusVoucherDiscount: '10% OFF + TASTING',
    participatingCount: 118,
    completedCount: 84,
    checkpoints: [
      {
        id: 'cp-eff-1',
        name: "Lord's Hill Historic District & Meetinghouse",
        town: 'Effingham',
        category: 'historic',
        description: 'Stunning Federal-style village square featuring the 1798 Meeting House, Paul Revere-style bell tower, and historic academy.',
        historicalNote: 'Lord’s Hill was the cultural and educational center of eastern New Hampshire in the early 1800s.',
        clue: 'Locate the granite boundary post near the village green historical placard.',
        address: 'Route 153 & Plantation Rd, Effingham, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-EFF-01',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-effingham-freedom-artisan&checkin=cp-eff-1',
        photoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-eff-2',
        name: 'Green Mountain Fire Tower Trailhead',
        town: 'Effingham',
        category: 'nature',
        description: 'Historic forest path leading to one of Carroll County’s most prominent fire watch peaks.',
        historicalNote: 'Constructed in the 1920s, the Green Mountain tower provided early smoke detection across 5 surrounding NH and Maine counties.',
        clue: 'Check the wooden kiosk at the trailhead parking turn-around.',
        address: 'High Mountain Rd, Effingham, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-EFF-02',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-effingham-freedom-artisan&checkin=cp-eff-2',
        photoUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-eff-3',
        name: 'Freedom Village Covered Footbridge & Mill Brook',
        town: 'Freedom',
        category: 'bridge',
        description: 'Charming pedestrian timber bridge arching over clear cascading trout waters of Cold Brook.',
        historicalNote: 'Freedom was originally settled for its fast-moving mill streams that powered local wool and lumber mills in the 1830s.',
        clue: 'Tap the wooden handrail NFC chip in the middle arch of the footbridge.',
        address: 'Village Road, Freedom, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-EFF-03',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-effingham-freedom-artisan&checkin=cp-eff-3',
        photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-eff-4',
        name: 'Effingham Valley Maple Grove & Artisan Stand',
        town: 'Effingham',
        category: 'artisan',
        description: 'Working wood-fired sugarhouse tapping ancient sugar maples and producing pure NH amber syrup.',
        historicalNote: 'Family-owned sugaring operation utilizing gravity feed lines and traditional iron woodstoves for three generations.',
        clue: 'Find the copper sap bucket at the front farmstand display.',
        address: 'Province Lake Rd, Effingham, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-EFF-04',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-effingham-freedom-artisan&checkin=cp-eff-4',
        photoUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Effingham Valley Maple',
        sponsorOffer: 'Free sample cup of maple syrup with any purchase'
      }
    ]
  },
  {
    id: 'hunt-wolfeboro-resort',
    title: 'Wolfeboro "America’s Oldest Summer Resort" Heritage Quest',
    slug: 'wolfeboro-resort-quest',
    town: 'Wolfeboro',
    region: 'Carroll County, NH',
    badgeName: 'Lakes Region Navigator',
    badgeIcon: '⛵',
    difficulty: 'Easy',
    estimatedDuration: '2 Hours',
    description: 'Walk the historic waterfront of Lake Winnipesaukee, rail trails, WWII museum artifacts, and artisan craft breweries.',
    theme: 'Lake Winnipesaukee Heritage & Maritime Culture',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 250,
    bonusVoucherTitle: '$5 Off Wolfeboro Artisan Treats & Brewery Flight',
    bonusVoucherCode: 'WOLFEBORO-LAKES-5',
    bonusVoucherDiscount: '$5.00 CREDIT',
    participatingCount: 230,
    completedCount: 167,
    checkpoints: [
      {
        id: 'cp-wolf-1',
        name: 'Wolfeboro Town Docks on Lake Winnipesaukee',
        town: 'Wolfeboro',
        category: 'scenic',
        description: 'The premier public gateway to Lake Winnipesaukee where the Mount Washington steamship docks.',
        historicalNote: 'Governor John Wentworth established Wolfeboro as America’s first summer resort in 1770 when building his lakeside estate.',
        clue: 'Look for the bronze nautical compass rose embedded near the town dock harbormaster kiosk.',
        address: '1 Lake St, Wolfeboro, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-WOLF-01',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-wolfeboro-resort&checkin=cp-wolf-1',
        photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-wolf-2',
        name: 'Cotton Valley Rail Trail Mile Marker 0',
        town: 'Wolfeboro',
        category: 'nature',
        description: 'Multi-use converted rail corridor connecting Lake Winnipesaukee all the way to Sanbornville.',
        historicalNote: 'Follows the historic Wolfeboro Railroad path built in 1872 to transport passengers and ice harvested from the lake.',
        clue: 'Find the granite mile marker "0.0" post by the old freight station.',
        address: 'Railroad Ave, Wolfeboro, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-WOLF-02',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-wolfeboro-resort&checkin=cp-wolf-2',
        photoUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-wolf-3',
        name: 'Wright Museum of WWII History Plaza',
        town: 'Wolfeboro',
        category: 'historic',
        description: 'Nationally recognized museum celebrating the home front and battlefield contributions of Americans during 1939-1945.',
        historicalNote: 'Houses an impressive collection of operational Sherman tanks, halftracks, and 1940s vintage storefront exhibits.',
        clue: 'Tap the kiosk plaque at the outdoor memorial courtyard entrance.',
        address: '77 Center St, Wolfeboro, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-WOLF-03',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-wolfeboro-resort&checkin=cp-wolf-3',
        photoUrl: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-wolf-4',
        name: 'Cate Park Bandstand & Lakeside Gardens',
        town: 'Wolfeboro',
        category: 'scenic',
        description: 'Lush terraced floral gardens, war memorials, and the waterfront gazebo hosting summer twilight concerts.',
        historicalNote: 'Donated to the town in memory of the Cate family, preserving unobstructed views of Wolfeboro Bay.',
        clue: 'Near the stone steps descending toward the water fountain.',
        address: 'Main St & Cate Park, Wolfeboro, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-WOLF-04',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-wolfeboro-resort&checkin=cp-wolf-4',
        photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-wolf-5',
        name: 'Lone Wolfe Craft Brewing & Community Tap',
        town: 'Wolfeboro',
        category: 'food_drink',
        description: 'Locally crafted ales, lagers, and community beer garden located in historic downtown Wolfeboro.',
        historicalNote: 'Brewed using pure New Hampshire mountain runoff water and locally sourced hops.',
        clue: 'Located at the beer garden entrance host stand.',
        address: '36 Mill St, Wolfeboro, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-WOLF-05',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-wolfeboro-resort&checkin=cp-wolf-5',
        photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Lone Wolfe Brewing',
        sponsorOffer: '$2 off your first draft flight with trail check-in'
      }
    ]
  },
  {
    id: 'hunt-conway-gateway',
    title: 'Conway & White Mountain Gateway Alpine Safari',
    slug: 'conway-alpine-safari',
    town: 'Conway',
    region: 'Carroll County, NH',
    badgeName: 'Gateway Alpine Scout',
    badgeIcon: '⛰️',
    difficulty: 'Moderate',
    estimatedDuration: '2.5 Hours',
    description: 'Explore the gateway to the White Mountains: Saco River rapids, Swift River Covered Bridge, Cathedral Ledge, and historic rail yards.',
    theme: 'Mountain Vistas, Covered Bridges & Rail Heritage',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 250,
    bonusVoucherTitle: '10% Off Mountain Gear or Sean Martin 4x4 Courier Services',
    bonusVoucherCode: 'CONWAY-ALPINE-10',
    bonusVoucherDiscount: '10% OFF',
    participatingCount: 195,
    completedCount: 132,
    checkpoints: [
      {
        id: 'cp-con-1',
        name: 'Swift River Covered Bridge Historic Site',
        town: 'Conway',
        category: 'bridge',
        description: 'One of New Hampshire’s most photographed paddleford truss bridges crossing the Swift River.',
        historicalNote: 'Built in 1870 after the 1869 flood washed away the original span; now preserved as a scenic pedestrian landmark.',
        clue: 'Look for the bronze historical marker on the east portal arch.',
        address: 'Passaconaway Rd & Swift River, Conway, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-CON-01',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-conway-gateway&checkin=cp-con-1',
        photoUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-con-2',
        name: 'Cathedral Ledge Granite Overlook',
        town: 'Conway',
        category: 'scenic',
        description: 'A 700-foot granite cliff providing sweeping views of the Saco River Valley and Kancamagus Highway peaks.',
        historicalNote: 'World-renowned rock climbing destination and nesting territory for peregrine falcons.',
        clue: 'Find the metal railing overlook platform near the summit road turnaround.',
        address: 'Cathedral Ledge Rd, North Conway, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-CON-02',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-conway-gateway&checkin=cp-con-2',
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-con-3',
        name: 'Conway Scenic Railroad Heritage Rail Yard',
        town: 'Conway',
        category: 'historic',
        description: 'Victorian-era 1874 train station and active heritage railroad operating vintage diesel and steam engines through Crawford Notch.',
        historicalNote: 'The Mountain Division rail was an engineering marvel carved through solid granite cliffs in the 1870s.',
        clue: 'Located next to the historic passenger boarding signal lamp.',
        address: '38 Norcross Circle, North Conway, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-CON-03',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-conway-gateway&checkin=cp-con-3',
        photoUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-con-4',
        name: 'Saco River Canoe & Kayak Launch Outpost',
        town: 'Conway',
        category: 'nature',
        description: 'Gentle crystal-clear waters and sandy river beaches running through Carroll County pine forests.',
        historicalNote: 'The Saco River served as a vital transportation artery for Native Americans and early lumber drives.',
        clue: 'Check the wooden river access guide board near the boat ramp.',
        address: 'East Conway Rd Saco Launch, Conway, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-CON-04',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-conway-gateway&checkin=cp-con-4',
        photoUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-con-5',
        name: 'Sean Martin 4x4 Mountain Recovery & Courier Hub',
        town: 'Conway',
        category: 'food_drink',
        description: 'Carroll County dispatch hub for heavy-duty 4x4 rural logistics, hot food delivery, and mountain towing.',
        historicalNote: 'Dedicated all-weather service keeping rural mountain roads connected during winter blizzards and spring mud season.',
        clue: 'Tap the Oasis 4x4 badge on the dispatch vehicle kiosk or call 508-507-0305.',
        address: 'Main St Dispatch Center, Conway, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-CON-05',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-conway-gateway&checkin=cp-con-5',
        photoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Sean Martin 4x4 Express',
        sponsorOffer: 'Priority dispatch and $5 tip match'
      }
    ]
  },
  {
    id: 'hunt-tamworth-arts',
    title: 'Tamworth Arts, Farmstands & Craft Spirits Circuit',
    slug: 'tamworth-arts-spirits',
    town: 'Tamworth',
    region: 'Carroll County, NH',
    badgeName: 'Tamworth Culture Seeker',
    badgeIcon: '🎭',
    difficulty: 'Easy',
    estimatedDuration: '1.5 Hours',
    description: 'Immerse in America’s oldest summer theatre, organic working farms, historic lyceums, and botanical craft distilleries.',
    theme: 'Summer Stock Theatre, Organic Agriculture & Craft Spirits',
    coverImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    totalPoints: 200,
    bonusVoucherTitle: 'Free Artisan Espresso or $5 Off Tamworth Spirits Tasting',
    bonusVoucherCode: 'TAMWORTH-CULTURE-5',
    bonusVoucherDiscount: '$5.00 CREDIT',
    participatingCount: 164,
    completedCount: 119,
    checkpoints: [
      {
        id: 'cp-tam-1',
        name: 'The Barnstormers Theatre (Historic Stage)',
        town: 'Tamworth',
        category: 'historic',
        description: 'Founded in 1931 by Francis Cleveland (son of US President Grover Cleveland), it is America’s oldest continuously running professional summer theatre.',
        historicalNote: 'Celebrated actors have performed here for over 90 seasons in the heart of Tamworth Village.',
        clue: 'Look for the bronze playbill case on the main theatre porch.',
        address: '104 Main St, Tamworth, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-TAM-01',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-tamworth-arts&checkin=cp-tam-1',
        photoUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'cp-tam-2',
        name: 'Tamworth Lyceum & Coffee Emporium',
        town: 'Tamworth',
        category: 'artisan',
        description: 'Community gathering hall, specialty coffee bar, artisan bookstore, and curated local provisions.',
        historicalNote: 'Revived 19th-century New England lyceum tradition where neighbors gather for lectures, music, and ideas.',
        clue: 'Tap the Oasis wooden counter coaster at the barista order bar.',
        address: '85 Main St, Tamworth, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-TAM-02',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-tamworth-arts&checkin=cp-tam-2',
        photoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Tamworth Lyceum',
        sponsorOffer: 'Free pastry upgrade with any specialty coffee'
      },
      {
        id: 'cp-tam-3',
        name: 'Tamworth Distilling & Botanical Barrel Garden',
        town: 'Tamworth',
        category: 'food_drink',
        description: 'Artisan craft distillery turning locally foraged botanical ingredients, pure spring water, and grains into award-winning spirits.',
        historicalNote: 'Located in the historic 1800s Tamworth Inn building overlooking the Swift River.',
        clue: 'Located at the outdoor botanical garden tasting terrace.',
        address: '15 Cleveland Hill Rd, Tamworth, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-TAM-03',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-tamworth-arts&checkin=cp-tam-3',
        photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
        sponsorName: 'Tamworth Distilling',
        sponsorOffer: 'Complimentary botanical mocktail or spirit tasting token'
      },
      {
        id: 'cp-tam-4',
        name: 'Remick Country Doctor Museum & Historic Farm',
        town: 'Tamworth',
        category: 'historic',
        description: 'A 200-year-old working agricultural homestead honoring father-and-son country doctors who served Carroll County residents.',
        historicalNote: 'Features historic apothecary herbs, historic livestock breeds, blacksmith shop, and self-guided walking farm pastures.',
        clue: 'Search the museum barn entrance bulletin kiosk.',
        address: '58 Cleveland Hill Rd, Tamworth, NH',
        pointsReward: 25,
        nfcTagId: 'NFC-HUNT-TAM-04',
        qrPayloadUrl: 'https://townraise.org/tourist-hunts?hunt=hunt-tamworth-arts&checkin=cp-tam-4',
        photoUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80',
      }
    ]
  }
];

export const INITIAL_USER_STAMPS: PassportStamp[] = [];
